### ISSUE TITLE
Vimperator broken in latest Nightly 41.0a1 (2015-05-22)

### ISSUE THREAD

**Issue by danemacmillan** [vimperator/vimperator-labs#231] opened 2015-05-22 13:31 UTC
It does not respond to any key shortcuts, and the theme, key bindings, and other customizations are not loaded, either. It is likely this is just an issue with today's build of Nightly, but in case the issue remains from this point forward, an issue should be documented.

**Comment by gkatsev** [comment] 2015-05-22 14:42
Is e10s enabled? Vimperator doesn't subtitles yet.
If it isn't e10s, I'll take a look.

**Comment by danemacmillan** [comment] 2015-05-22 16:26
No, it's disabled.

**Comment by gkatsev** [comment] 2015-05-22 16:28
Cool, thanks. Did you notice if vimperator printed out any messages in the status bar?

**Comment by danemacmillan** [comment] 2015-05-22 20:13
It doesn't display any errors. The status bar is just white and displays the current page's URL in black. I tried a variety of key combinations and entering different modes, but it does nothing.

**Comment by danemacmillan** [comment] 2015-05-23 22:42
Sadly, it's also broken in today's build.

**Comment by Mine02C4** [comment] 2015-05-27 02:53
I have same problem.
In my environment, there are some below messages in Browser Console.
```
11:20:49.508 options.get(...) is null1 autocommands.js:110:0
```
```
11:20:50.587 TypeError: options.get(...) is null1 autocommands.js:110:12
```

**Comment by Segaja** [comment] 2015-05-27 05:05
I have the same issue with nightly since yesterday. Here is the console output when starting firefox: http://pastie.org/private/tqqfxnvu7l37opn8j8qa

Seems like some deprecated stuff was now finally removed.

**Comment by danemacmillan** [comment] 2015-06-11 23:15
Are there any updates on this? The Nightly codebase is moving to DevEdition/Aurora in two weeks.

**Comment by gkatsev** [comment] 2015-06-11 23:29
Not yet but I'll finally have time to start looking at it starting with this weekend.

**Comment by danemacmillan** [comment] 2015-06-13 02:13
Here is some additional debug information from the browser console:
```
22:12:07.502 unreachable code after return statement developurr.js:295:4
22:12:07.544 unsafe CPOW usage worker.js:127:0
22:12:07.545 unsafe CPOW usage utils.js:259:0
22:12:07.551 unsafe CPOW usage utils.js:78:0
22:12:07.552 unsafe CPOW usage worker.js:150:0
22:12:07.562 options.get(...) is null autocommands.js:110:0
22:12:07.690 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.7.1.js:3:0
22:12:07.757 options.get(...) is null autocommands.js:110:0
22:12:38.044 options.get(...) is null autocommands.js:110:0
22:12:43.486 ReferenceError: util is not defined liberator.js:250:16
22:12:52.694 unsafe CPOW usage browser.js:15372:0
22:12:52.762 unsafe CPOW usage tabbrowser.xml:542:0
22:12:52.763 Error: operation not possible on dead CPOW tabbrowser.xml:542:0
22:12:52.770 unsafe CPOW usage worker.js:127:0
22:12:52.770 unsafe CPOW usage utils.js:259:0
22:12:52.773 unsafe CPOW usage utils.js:78:0
22:12:52.774 unsafe CPOW usage worker.js:150:0
22:12:53.448 util is not defined liberator.js:250:0
22:12:53.949 unsafe CPOW usage buffer.js:378:0
22:12:53.950 ReferenceError: util is not defined liberator.js:250:16
22:12:53.953 util is not defined liberator.js:250:0
22:12:53.958 unsafe CPOW usage buffer.js:378:0
22:12:53.960 ReferenceError: util is not defined liberator.js:250:16
22:12:54.046 OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.6.20
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
FBO Texture Target: TEXTURE_2D
```

**Comment by dvcrn** [comment] 2015-06-14 12:48
First time user here, coming from vimium for chrome. Getting the following error line in developer edition.
![screen shot 2015-06-14 at 9 45 49 pm](https://cloud.githubusercontent.com/assets/688326/8148586/06a0a0b2-12df-11e5-9e4b-d5291d4a28f2.png)

**Comment by hanyas** [comment] 2015-06-16 22:18
same problem here! 

liberator: Error loading script commandline.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script mappings.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script util.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script bookmarks.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:70:5
@chrome://liberator/content/liberator-overlay.js:6:2

**Comment by w1ld** [comment] 2015-06-19 07:48
Looks like I have something connected on Thunderbird 38.0.1, Mutator 1.2. Mutator does not function: no status bar, no keys working. Errors:

	Timestamp: 19.06.2015 10:41:00
	Error: Error opening input stream (invalid filename?): liberator://template/chrome://liberator/content/mail.js
	Source File: chrome://liberator/content/liberator-overlay.js
	Line: 24
	
	Timestamp: 19.06.2015 10:41:00
	Error: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChannel.open]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: jar:file:///C:/Users/wild/AppData/Roaming/Thunderbird/Profiles/qbyfwg2v.default/extensions/muttator@mozdev.org.xpi!/components/protocols.js :: Liberator.prototype.newChannel :: line 233"  data: no]
	Source File: jar:file:///C:/Users/wild/AppData/Roaming/Thunderbird/Profiles/qbyfwg2v.default/extensions/muttator@mozdev.org.xpi!/components/protocols.js
	Line: 249
	
	Timestamp: 19.06.2015 10:41:00
	Error: plugins is not defined
	Source File: chrome://liberator/content/liberator-overlay.js -> liberator://template/chrome://liberator/content/io.js
	Line: 10
	
	Timestamp: 19.06.2015 10:41:00
	Error: redeclaration of let usage
	Source File: chrome://liberator/content/liberator-overlay.js -> liberator://template/chrome://liberator/content/liberator.js
	Line: 1720, Column: 24
	Source Code:
	                    var usage = template.genericOutput(config.name + " Usage", usage
	
	
	Timestamp: 19.06.2015 10:41:00
	Error: redeclaration of var str
	Source File: chrome://liberator/content/liberator-overlay.js -> liberator://template/chrome://liberator/content/commandline.js
	Line: 1469, Column: 24
	Source Code:
	                    let str = CommandLine.echoArgumentToString(str, true);

**Comment by dvcrn** [comment] 2015-07-01 14:27
Persists in a2

**Comment by MoSal** [comment] 2015-07-03 17:42
To confirm what @dvcrn reported.
Developer Edition is now broken. I had to downgrade to a beta candidate.

**Comment by Darksonn** [comment] 2015-07-04 08:59
I confirm what @dvcrn repoted as well.

**Comment by Darksonn** [comment] 2015-07-04 09:40
The following is printed in my browser console with an error mark when starting a2 with the plugin compiled from source:

    11:33:53.760 DEPRECATION WARNING: FUEL is deprecated, you should use the add-on SDK instead.
    You may find more details about this deprecation at: https://developer.mozilla.org/Add-ons/SDK/
    jar:file:///opt/firefox/browser/omni.ja!/components/fuelApplication.js 1458 Application
    jar:file:///opt/firefox/browser/omni.ja!/components/fuelApplication.js 726 af_ci
    chrome://liberator/content/io.js 333 IO<.init
    chrome://liberator/content/base.js line 317 > eval 14 io
    chrome://liberator/content/modules.js 90 load
    self-hosted 210 forEach
    chrome://liberator/content/modules.js 119 onload
    null 0 null
    1 Deprecated.jsm:79:0

**Comment by t0b1nux** [comment] 2015-07-08 16:40
I'm using Firefox 42.0a1 (2015-07-08) (self-compiled) and its showing a status bar but don't work. I can't even open liberator://help/options
Here is what Firefox launched in a terminal say: 
```
liberator: Error loading script commandline.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script mappings.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script util.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script bookmarks.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:70:5
@chrome://liberator/content/liberator-overlay.js:6:2
```
I'm using Firefox on ArchLinux  x86_64 with Linux kernel 4.1.1-1.

**Comment by gkatsev** [comment] 2015-07-11 05:33
I think of the issues might be that XPCOM has been disabled: https://blog.mozilla.org/addons/2015/05/04/dropping-support-for-binary-components/

**Comment by gkatsev** [comment] 2015-07-11 18:57
I have a WIP PR for fixing thiese issues: #242

**Comment by nodar-chkuaselidze** [comment] 2015-07-17 06:32
Firefox 41.0a2 - OSX 10.10.3
Same problem:
```
liberator: Error loading script commandline.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script mappings.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script util.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

liberator: Error loading script bookmarks.js: SyntaxError: expected expression, got keyword 'let'
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:70:5
@chrome://liberator/content/liberator-overlay.js:6:2
```

**Comment by gkatsev** [comment] 2015-07-17 14:59
@nodar-chkuaselidze this sounds like it's fixed in my branch #242. Would be awesome if you can try it out.

**Comment by e12e** [comment] 2015-07-17 20:59
FYI, this seems to be working for me too on windows 8.1 64bit / FF 41.0a2.

Couldn't build it under windows though, both master and fixup-nightly errors out with:

  $ make xpi
  Building XPI...
  Including en-US documentation
  Including ja documentation
  Replacing ###VERSION### and ###DATE### tags
  File not found - *.css
  make: *** [xpi] Error 2

This is under cygwin -- and the combination that got farthest along (tried mingw64 and the stuff that comes with git/bash). No problems building on Debian 7/old stable (the server that was easiest to try - didn't try on 8/stable -- but presumably builds fine there too). Probably should file a separate bug for instructions on how to build under windows -- assuming it's supposed to be supported at all? (A pointer to an installer/setup w/make++ that's expected to work would go a long way).

**Comment by gkatsev** [comment] 2015-07-17 21:16
Yeah, no idea whether building on windows was ever supported.

**Comment by zklinger** [comment] 2015-07-19 23:19
@gkatsev Vimperator should build on Windows under Cygwin. Two additional packages, 'make' and 'zip' are required. Have successfully built it on 64 bit Windows 8.1 with the latest Cygwin installed. 

@Mine02C4 The make process is expected to use /usr/bin/find. You may have some other 'find' in your path that gets run instead of /usr/bin/find. What do you get if you run
```bash
which find
```
in your Cygwin terminal?

You should get something like
```bash
$ which find
/usr/bin/find
```
Also worth checking the version of 'find'
```bash
$ find --version
find (GNU findutils) 4.5.12
Packaged by Cygwin (4.5.12-1)
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS(FTS_CWDFD) CBO(level=2)
```

**Comment by Mine02C4** [comment] 2015-07-20 00:33
@zklinger I use both cygwin and CentOS  7. I sometimes build on cygwin, but mostly build on CentOS.

Cygwin
```
$ which find
/usr/bin/find
$ find --version
find (GNU findutils) 4.5.12
Packaged by Cygwin (4.5.12-1)
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
有効になっている機能: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS(FTS_CWDFD) CBO(level=2)
```

CentOS

```
$ which find
/usr/bin/find
find (GNU findutils) 4.5.11
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
有効になっている機能: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION SELINUX FTS(FTS_CWDFD) CBO(level=2) 
```
"有効になっている機能" is "Features enabled" in English.

**Comment by hanyas** [comment] 2015-08-13 17:37
same problem in the latest beta version now. I have the latest vimp version from the firefox addon-site

**Comment by t0b1nux** [comment] 2015-08-13 17:41
You must compile yourself vimperator from the dedicated branch fixup-nightly, not use the old version on the firefox addons website.

**Comment by gkatsev** [comment] 2015-08-13 17:42
I'll try and get an alpha release out this weekend.

**Comment by icylogic** [comment] 2015-08-14 09:55
I've just compiled the fixup-nightly and installed it on Firefox 41 beta (I should go to about:config and turn off `xpinstall.signatures.required`).

It works but `set gui` does not works well. Only `set gui=all` and `set gui=none` take effects, and other parameters like `[no]bookmarks`,`[no]tabs` are `Invalid argument`. Could you test this command? Is this a common bug (due to changes of firefox's api)?

**Comment by vaibhavsagar** [comment] 2015-08-14 13:07
I can confirm that `set gui=nonavigation` does not work.

**Comment by Segaja** [comment] 2015-08-16 05:31
Firefox Nightly is broken once more. Even with the `fixup-nightly` branch from vimp. This time it is `Firefox Nightly 43.0a1 (2015-08-15)`. The error in the console is the following: 

```
liberator: Error loading script config.js: TypeError: Array.splice is not a function
Module@chrome://liberator/content/modules.js:58:16
@chrome://liberator/content/config.js:8:16
load@chrome://liberator/content/liberator-overlay.js:20:17
@chrome://liberator/content/liberator-overlay.js:41:1
@chrome://liberator/content/liberator-overlay.js:6:2

JavaScript error: chrome://liberator/content/liberator-overlay.js, line 69: TypeError: modules.Config is undefined
JavaScript warning: resource://firebug/locale.js, line 68: flags argument of String.prototype.{search,match,replace} is deprecated
JavaScript error: chrome://liberator/content/modules.js, line 72: TypeError: Config is undefined
```

**Comment by gregist** [comment] 2015-08-16 06:14
I can confirm what @Segaja reported. None of the keyboard shortcuts are working right now. EVEN ```:```

**Comment by Segaja** [comment] 2015-08-16 08:17
Some comment from #extdev/mozilla irc network:

```
10:04:04 < The_8472> you really shouldn't be splicing arguments. it's bad for performance aiui. maybe let localArgs = Array.from(arguments)
10:04:12 < The_8472> and then you can localArgs.splice(...)
10:05:32 < The_8472> or use the spread operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator
10:05:33 < freonbot> [ Spread operator - JavaScript | MDN ] - developer.mozilla.org
```

**Closed** 2015-08-24 01:30 UTC
Labels: bug

**Comment by gkatsev** [comment] 2015-08-24 04:26
Fixed in master. Expect a release soon.
