### ISSUE TITLE
vimperator: smarter gi implementation

### ISSUE THREAD

**Issue by pale3** [vimperator/vimperator-labs#449] opened 2016-03-06 11:49 UTC
When executing `gi` on let's say google, and textarea is alreay filled with some strings, gi needs to go in position of `string.length + 1` rather then on `0` position (beginning of string).

**Comment by timss** [comment] 2016-03-06 13:03
Thanks for reporting, but this is a duplicate of #192 and #345. 

Please use `noremap gi gi<End>` if you want this behavior.

**Closed by timss** 2016-03-06 13:03 UTC

**Comment by pale3** [comment] 2016-03-06 13:32
thx
