### ISSUE TITLE
Hint links "f" doesn't work in FF56

### ISSUE THREAD

**Issue by QuAzI** [vimperator/vimperator-labs#801] opened 2017-10-14 13:38 UTC
BUG: 
Firefox 56.0.1 AMD64 ru
Vimperator 3.16.0

When I press "f" nothing highlited. Search string in bottom opened instead.
Please check video
http://storage.mydataprovider.com/screenshots/yar/2017-10-14_16-35-27_uw3LYOZt.webm

Also "o" opens links list but it is very strange (in end of video)
![2017-10-14_16-40-17_pyea2fih](https://user-images.githubusercontent.com/1897605/31576177-7fb541b4-b0fe-11e7-89a6-2774f3f8491a.png)

Also "Settings" doesn't work
http://storage.mydataprovider.com/screenshots/yar/2017-10-14_16-28-29_LKzye46S.webm

**Comment by vfricou** [comment] 2017-10-14 17:47
Same problem here with sames versions of firefox (Not RU) and vimperator.

**Comment by sunyta2** [comment] 2017-10-15 01:42
For me either. same problem that is not working F key. Please fix and return F key function. It's crucial function in browsing.

**Comment by Yuhta** [comment] 2017-10-16 00:01
Same here.

**Comment by gorthad1534** [comment] 2017-10-16 12:02
Same problem with F key.

**Comment by dboonz** [comment] 2017-10-16 12:33
+1

**Comment by silvadanilo** [comment] 2017-10-17 10:15
+1

**Comment by zonxin** [comment] 2017-10-22 07:40
+1

**Comment by SammysHP** [comment] 2017-10-23 17:24
Duplicate of #796.

**Closed by SammysHP** 2017-10-23 17:24 UTC
