### ISSUE TITLE
Can't escape from `chat.stackexchange.com`

### ISSUE THREAD

**Issue by zzt93** [vimperator/vimperator-labs#80] opened 2014-11-02 01:08 UTC
As the title says, when I talk with others in that website, I can't escape by pressing 'Esc`.

**Comment by wldcordeiro** [comment] 2015-03-04 08:48
This seems to be an issue on multiple sites. I've found that the same occurs in Slack. Maybe this issue should be made into a meta issue with a list of sites affected? I'm not sure if it's something Vimperator can fix or not though, the sites may be overriding something that breaks the functionality?

**Comment by maxauthority** [comment] 2015-03-08 22:07
We have even tried a fix which tried to fix that (and other sites') issue
with Esc but it had severe regressions so we had to back it out. We'd be
very happy for someone to provide an updated patch.

**Comment by blueyed** [comment] 2015-09-01 21:26
https://github.com/vimperator/vimperator-labs/issues/46 has more information in this regard.

**Comment by timss** [comment] 2016-03-01 22:15
Seems to be working as of Firefox 44.0.2 and Vimperator 3.12.0. Closing.

If it's still an issue, please notify me and I'll reopen and investigate further.

**Closed by timss** 2016-03-01 22:15 UTC
