### ISSUE TITLE
'gui' option no longer recognized

### ISSUE THREAD

**Issue by lsm5** [vimperator/vimperator-labs#375] opened 2016-01-23 23:47 UTC
I just updated to Firefox 44.0. Now I see that the option 'gui' is no longer recognized.

My .vimperatorrc has `set gui=none` which worked just fine before the upgrade.

**Comment by aldrik** [comment] 2016-01-26 18:48
I also came across this, it seems like a duplicate of #352 (following the steps there fixes the issue).

**Comment by gkatsev** [comment] 2016-01-26 18:50
@aldrik thanks. Yeah, seems like the issue is that vimperator is out of date. I'll be taking time tonight to make sure that everything works and releasing a new version of vimperator.
Closing as a dupe of #352 for now.

**Closed by gkatsev** 2016-01-26 18:50 UTC

**Comment by lsm5** [comment] 2016-01-26 18:58
@aldrik @gkatsev rocking, thanks!
