### ISSUE TITLE
Vimperator don't work in Firefox Beta. Not e10s.

### ISSUE THREAD

**Issue by ghost** [vimperator/vimperator-labs#568] opened 2016-08-05 20:53 UTC
##### Issue type:

- Version compatibility
##### Version:

```
Vimperator 3.15, Nightly 51.0a2, e10s disabled.
```
##### Description:

Mappings and commandline don't work.
In browser console it's showing that `ReferenceError: tabs is not defined`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined

**Comment by tinkerttoy** [comment] 2016-10-30 17:19
You also can't use the :help command.

**Comment by tinkerttoy** [comment] 2016-10-31 21:01
I think I found the problem. See #211. Developer Edition has e10s enabled by default, so that'd explain why it's broken. Looks like e10s support ought to get moved up the priority list.

**Comment by gkatsev** [comment] 2016-10-31 23:32
Going to close as a duplicate of #211 then. e10s is at the top but there's not a lot of people who know a lot about e10s and also have time to work on it unfortunately :(

**Comment by stepshal** [comment] 2016-11-01 02:47
@tinkerttoy @gkatsev it's not e10s issue, it's not working with e10s disabled, i pointed out that in issue.

**Comment by gkatsev** [comment] 2016-11-01 03:16
Oh, I see. Sorry, re-opening.

**Comment by deathbeam** [comment] 2016-11-01 13:02
Same problem here, most of stuff is working, except everything related to tabs and preference pane.

**Comment by RomanHargrave** [comment] 2016-11-08 18:15
Same, as above.

List of things that are working here, at least that I have noticed:

* Open in focused tab (`:open`)
* `winclose`, `winopen`, `winonly`, and `window`

Everything else probably is too.

List of things not working

* All commands named like `tab*` are not even present


Version: HEAD

**Comment by teranex** [comment] 2016-11-16 09:54
I updated to Firefox 51 beta yesterday and Vimperator (particularly :tabopen) is broken.

:version
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by TimePower** [comment] 2016-11-16 15:17
Same problem on Fx 51 Beta, f & c-n/p not work, e10s is disable.
The console show 
`
liberator: Error loading script tabs.js: SyntaxError: non-generator method definitions may not contain yield
load@chrome://liberator/content/liberator-overlay.js:17:17
@chrome://liberator/content/liberator-overlay.js:66:5
@chrome://liberator/content/liberator-overlay.js:6:2
`

**Comment by timss** [comment] 2016-11-16 22:38
Protip: use the ESR instead of betas or bleeding edge releases, for better compatability..

**Comment by SammysHP** [comment] 2016-11-24 14:15
@timss Which does not work when using own builds of Vimperator (e.g. development / custom modifications) if you don't want to send every build to Mozilla for signing (which works automatically with my makefile modification, but takes a 10-60 seconds longer).

**Comment by nornagest** [comment] 2017-01-22 10:52
I have just noticed this problem too, after upgrading Firefox.

Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; FreeBSD amd64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by Nefari0uss** [comment] 2017-01-22 18:26
@timss  I don't think telling people to switch to ESR is the best way of going about the E10s issue. All it does is kick it down the road.

**Comment by timss** [comment] 2017-01-24 09:03
@Nefari0uss It most certainly is not, but it's one currently viable, working option. Although at this point not for long, as the next ESR release Firefox 52 is set to release March 2017:

- https://www.mozilla.org/en-US/firefox/organizations/faq/
- https://wiki.mozilla.org/RapidRelease/Calendar

As far as e10s or WebExtensions development goes, the status unfortunately hasn't changed too much since I wrote this back in September. I don't personally have the time to change much about that. Some PRs come in from time to time (thanks!), and a couple recently got merged by @maxauthority. But the e10s/WE issue still stands. 

- https://github.com/vimperator/vimperator-labs/issues/211#issuecomment-249181301

**Comment by sandermarechal** [comment] 2017-01-25 08:30
Firefox 51 was released today, breaking Vimperator as described. Any update on a fix?

**Comment by SammysHP** [comment] 2017-01-25 10:40
Firefox 51 is not in the Arch repository yet, so I cannot test. This might fix it, but there are also a lot of other generator functions without `function*`. I tried to fix all but then vimperator didn't work at all.

```diff
diff --git a/common/content/tabs.js b/common/content/tabs.js
index 8410e325..89948885 100644
--- a/common/content/tabs.js
+++ b/common/content/tabs.js
@@ -52,7 +52,7 @@ const Tabs = Module("tabs", {
      * @property {Iterator(Object)} A genenerator that returns all browsers
      *     in the current window.
      */
-    get browsers() {
+    browsers: function* () {
         let browsers = config.tabbrowser.browsers;
         for (let i = 0; i < browsers.length; i++)
             yield [i, browsers[i]];
```

**Comment by ma8ma** [comment] 2017-01-25 14:56
@SammysHP Looks good to me. The patch makes to work the tab operations on Firefox Developer Edition 52.0a2  :smile:

**Comment by SammysHP** [comment] 2017-01-25 16:03
There should be other functions that are not working. For example:

- `:bmarks`
- Directory completion
- Various preferences and option functions
- Some buffer actions

I haven't traced all calls so I don't know where functions are used (there are some that are not used at all!). Simply adding the star to all functions containing a `yield` will result in many errors and Vimperator won't load at all. I don't know what's the reason for that because functions with `yield` were (legacy) generator functions and adding the star shouldn't break it.

As I have very limited time at the moment (master's thesis) I cannot dig into this further. Maybe some JavaScript expert can have a look at this issue.

**Comment by DarkPrinceFrost** [comment] 2017-01-27 19:41
```diff
diff --git a/common/content/tabs.js b/common/content/tabs.js
index 8410e32..89f8fea 100644
--- a/common/content/tabs.js
+++ b/common/content/tabs.js
@@ -52,7 +52,7 @@ const Tabs = Module("tabs", {
      * @property {Iterator(Object)} A genenerator that returns all browsers
      *     in the current window.
      */
-    get browsers() {
+    browsers: function*() {
         let browsers = config.tabbrowser.browsers;
         for (let i = 0; i < browsers.length; i++)
             yield [i, browsers[i]];
@@ -66,7 +66,7 @@ const Tabs = Module("tabs", {
     /**
      * @property {Object} The local options store for the current tab.
      */
-    get options() {
+    options: function*() {
         let store = this.localStore;
         if (!("options" in store))
             store.options = {};
```

Adding on to the patch suggest by @SammysHP with the options function fixed the majority of the issues I was encountering with vimperator not working.

If you don't want to watch for the release:
* Clone repo
* Apply patch above
* Run `make`
* Locate `extensions/vimperator@mozdev.org.xpi` that is currently in use and replace it with the new xpi created in `make` command above
* Restart firefox
* Win

**Comment by ksalman** [comment] 2017-01-27 20:26
@DarkPrinceFrost Thanks for the instructions. I tried it but Firefox 51 is still complaining that the extension could not be verified, even after changing `xpinstall.signatures.required` to False. Any ideas?

**Comment by Wiles** [comment] 2017-01-27 21:10
@ksalman You'll need to install the Developer Edition of Firefox. Other editions ignore `xpinstall.signatures.required`.

**Comment by ksalman** [comment] 2017-01-27 21:22
@DarkPrinceFrost Oh I see. Thanks.

**Comment by samrocketman** [comment] 2017-01-28 05:50
Upgraded to Firefox 51 in Ubuntu and encountered this as well.  Currently ingesting the comments but figured I would add that Firefox 51 has hit Ubuntu 14.04 stable package updates.  When I attempt to use the `r` key (refresh) among others I get the `ReferenceError: tabs is not defined` issue.  Checking for add-on updates does not resolve the problem, either.

**Comment by SammysHP** [comment] 2017-01-28 07:58
Because there is no update yet. @ma8ma seems to work on this issue and fixed not only generators, but for...in as well!

It is really annoying when the syntax of a language changes. Especially this high level / syntactic sugar. Deprecation is one thing, but removing it is different.

**Comment by LIttleAncientForestKami** [comment] 2017-01-28 11:25
Ave!

## Tab opening workaround
This doesn't require reinstalling extension or changing browser edition, though it doesn't restore `tabs`, so all commands relying on them are still broken. So, easier to have, less powerful than what @DarkPrinceFrost proposes [above](https://github.com/vimperator/vimperator-labs/issues/568#issuecomment-275755483).

1. Open your `.vimperatorrc` file (GNU/Linux: `/home/username/.vimperatorrc`)
2. Add this:
```
" Example keybinding: xt
nmap xt :extraTab<SPACE>
    
command! extraTab -nargs=1 -description "Open an extra tab" :js extraTab("<args>");
    
:js <<EOF
function extraTab(args) {
    liberator.open(args, liberator.NEW_TAB)
}
EOF
```

**Comment by leftaroundabout** [comment] 2017-01-28 11:40
@ksalman `xpinstall.signatures.required := false` worked for me (non-developer version of Firefox). It didn't itself enable vimperator again, but it allowed me to enable it in the Tools/Add-ons listing.

**Comment by SammysHP** [comment] 2017-01-28 11:49
@leftaroundabout Then you have a non-official version of Firefox.

**Comment by ohjames** [comment] 2017-01-28 12:59
I've been using the `firefox-unbranded` builds from Mozilla (`firefox-unbranded-bin` in the arch AUR). This pegs you to about the same version as the official build of firefox but lets you install unsigned extensions. `t` and `f` and `F` are broken at least, making vimperator basically unusable.

**Comment by gyphub** [comment] 2017-01-28 14:34
The patch posted by DarkPrinceFrost https://github.com/vimperator/vimperator-labs/issues/568#issuecomment-275755483 fixes most issues (Thank you!). There are exceptions caused by `getString` but Vimperator works.

Create a patch file from the posted diff, apply it, make. In `about:config` set `xpinstall.signatures.required` to `false` and from the add-ons tab `Install Add-on From File...` in the `downloads` directory.

Vimperator:	3.15.0 (created: 2017/01/28 15:06:08)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by SammysHP** [comment] 2017-01-28 15:40
@ma8ma Great work in your branch! Seems that there is only very few left that must be fixed. Any idea how long it will take?

**Comment by ma8ma** [comment] 2017-01-28 18:13
I've finished work for codes, PR candidate exists in [my repo](https://github.com/ma8ma/vimperator-labs/pull/1).
Would you be able to tell me if you find necessary for modification about typo, source comments, commit messages and more?

**Comment by stemar94** [comment] 2017-01-28 19:54
@ma8ma 
Thank you for working on this.
> Would you be able to tell me if you find necessary for modification about typo, source comments, commit messages and more?
I would probably condense these 14 commits into 1-3.

**Comment by SammysHP** [comment] 2017-01-28 22:34
Yes, squashing them into one commit would be great (current messages basically just say "update file xyz", all with the same modifications). Also it would be great to identify all parts that still not work and list them in the commit message or the pull request.

**Comment by chocolateboy** [comment] 2017-01-29 03:22
Instructions for building this can be found in `vimperator/private.properties.in`.

You'll need an [AMO API key](https://addons.mozilla.org/en-US/developers/addon/api/key/) and [`jpm`](https://github.com/mozilla-jetpack/jpm):

    npm install -g jpm

Then:

    git clone https://github.com/ma8ma/vimperator-labs ma8ma-vimperator-labs
    cd ma8ma-vimperator-labs
    git checkout update-generator-function # git >= 1.7.2
    cd vimperator
    cp private.properties.in private.properties

Then edit `private.properties` so that it looks something like:

### private.properties

```Makefile
VERSION       := $(VERSION).$(shell date '+%Y%m%d%H%M%S')
UUID           = vimperator@<uniqueid> # e.g. vimperator@<yourname>.example.com
AMO_API_KEY    = <your API key> # AKA "Issuer"
AMO_API_SECRET = <your API secret>
UPDATE_URL     =
UPDATE_URL_XPI =
```

You might also need to bump the `MAX_VERSION` in the `Makefile`.

Then run:

    make sign

The signed XPI should appear in `../downloads/vimperator-3.15.0.201701*-signed.xpi`. It should also be available for download in your AMO developer account.

**Comment by tgy** [comment] 2017-01-30 09:07
@chocolateboy thanks a lot for the instructions, it worked smoothly :)

**Comment by SammysHP** [comment] 2017-01-30 10:09
There's still an issue with the ssl status indicator which is not shown at all.

```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: XStringBundle :: getString :: line 21"  data: no]  (unbekannt)
	getString XStringBundle
	updateSSLState chrome://liberator/content/statusline.js:245:31
	StatusField<.update chrome://liberator/content/statusline.js:63:13
	updateField chrome://liberator/content/statusline.js:221:13
	onSecurityChange chrome://liberator/content/buffer.js:247:13
	callListeners chrome://browser/content/tabbrowser.xml:490:24
	_callProgressListeners chrome://browser/content/tabbrowser.xml:505:13
	updateCurrentBrowser chrome://browser/content/tabbrowser.xml:1118:15
	onselect chrome://browser/content/browser.xul:1:44
	set_selectedIndex chrome://global/content/bindings/tabbox.xml:664:13
	set_selectedPanel chrome://global/content/bindings/tabbox.xml:683:13
	set_selectedIndex chrome://global/content/bindings/tabbox.xml:399:15
	set_selectedItem chrome://global/content/bindings/tabbox.xml:431:34
	_selectNewTab chrome://global/content/bindings/tabbox.xml:476:11
	advanceSelectedTab chrome://global/content/bindings/tabbox.xml:523:13
	handleEvent chrome://global/content/bindings/tabbox.xml:153:19
```

**Comment by dcrozz** [comment] 2017-01-30 15:20
It seems that though I replace the xpi for FirefoxDeveloperEdition by following the steps listed by @DarkPrinceFrost , the vimperator works for a minute but so many error messages pop-up such as `TypeError: 'stopPropagation' called on an object that does not implement interface Event.` or `TypeError: m.getClientRects is not a function.` from time to time, and the hotkey I set such as `map H <C-p>` doesn't work accidentally.
The system I use is osx 10.11.6, Firefox 51.0.1 (64-bit).

**Comment by mwelt** [comment] 2017-01-30 21:03
@chocolateboy Somehow your instruction yields to 
![screen shot 2017-01-30 at 22 02 15](https://cloud.githubusercontent.com/assets/468177/22441478/d38d674e-e737-11e6-8296-68aeb3ea8b68.png)

Any suggestions, what i might do wrong here?

**Closed** 2017-01-31 08:08 UTC
Labels: compatibility

**Comment by timss** [comment] 2017-01-31 10:10
https://github.com/vimperator/vimperator-labs/pull/675#issuecomment-276303232

**Comment by chelmuth** [comment] 2017-01-31 13:32
Great to see this issue fixed. Is there already a plan when it will be available from https://addons.mozilla.org/en-US/firefox/addon/vimperator/?

**Comment by boreq** [comment] 2017-02-02 19:04
I think it is a bit weird that you decided to sit on the information that Vimperator is broken in the new stable release of Firefox and did nothing. As far as I can see that information was available for months and yet nothing was done about it untill today (okay, a commit was made but that doesn't mean much without the new Vimperator release). I find this a bit unprofessional for an addon with 30000 users. And as it is the major bug is still present after several days, which frankly I find quite annoying. I think some kind of a change to your relase process would be a good idea.

**Comment by SammysHP** [comment] 2017-02-02 19:14
30000 users vs 0 developers should explain it. But thanks that you want help us in the future. I look forward to see some nice commits fixing some of the issues. :)

**Comment by chelmuth** [comment] 2017-02-02 20:02
Isn't vimperator an admittedly successful, widely-adopted open-source project backed by diligent volunteers? I don't think it's fair to apply *professional* (whatever that means) standards in this case. It would be fair if anybody who's annoyed by a shortcoming would get started fixing the bug and contribute to the project. I myself did not pay anything for an addon that makes Firefox usable for years now and so I'm pretty glad it is still maintained while others just vanished. Thanks devs for your hard work!

**Comment by rwestlund** [comment] 2017-02-02 20:16
+1.  You don't get to complain about things you get for free.  I think it's pretty awesome that vimperator works 99.99% of the time, and all I had to do was click install :)

**Comment by timss** [comment] 2017-02-02 20:17
Much like @chelmuth said, "unprofessional" is exactly what Vimperator and most other Firefox addons are. The work done by previous and current contributors is done in our spare time, for free. It should go without saying, but such entitlement is not only misplaced, but also an annoyance in the open source community that contributors and maintainers should be spared.

**Comment by ClosetSquirrel** [comment] 2017-02-02 20:28
I'm in the situation that I simply don't have the time to contribute to vimperator myself, I'd imagine others are in the same situation. I'm willing to do what I can: give money to help with development (in a way that vimperator stays open source, rather than become paid software). The epub-reader addon is in a similiar situation as vimperator: it needs a rewrite w.r.t. to the changes planned by Mozilla. The dev behind it started a kickstarter project[1] so he can work full time on doing said rewrite. Might this be an option for vimperator? Kickstart money to either hire a dev or enable an existing dev to spend time on a rewrite?

[1] https://www.kickstarter.com/projects/569473473/epubreader-for-future-firefox

**Comment by vlcinsky** [comment] 2017-02-02 20:40
This shows, some things are not only technical, but also require some managerial effort.

Some people like coding, others are able to manage all the stuff around funding. I can understand, some great coders hate any organizational stuff.

It would be great to have vimperator functional in future - with Mozilla planned switch. Demand is very strong (vimperator is in muscles of many very productive people) and I am sure the chance for enough funds is very high.

My proposal is:
- is main developer willing to organize the funding?
- if not, is there anybody, who would be willing to help him with that? If so, can they agree on setting up the campaign together?
 
PS: Personally, I have no experience with such project, so I cannot serve myself. Just wanted to propose possible path of development (and yes, count with my 50 USD contribution if it ever starts - it was already worth 2x10 USD in past).

**Comment by wmorrell** [comment] 2017-02-02 21:13
What main developer? There currently are none. It's a project that was open-sourced a long time ago, and a few enthusiasts here and there continue to volunteer time to maintain it. It's nobody's day-job. If you feel like donating, there are PayPal and Flattr buttons on the vimperator.org website. Please do not encourage setting up alternate funding, that will only draw donations away and potentially direct the funding to scammers or less scrupulous individuals.

The current maintainers have repeatedly said, funding is not the issue. Work submitting patches, or re-implementing as WebExtensions instead of XUL, is needed. Experience is not required; you get the experience by doing things you have not done before. If you have the time, great! Lots of people will appreciate your effort. But please, if you do not have the time, refrain from complaining about the efforts of the existing volunteers.

**Comment by vlcinsky** [comment] 2017-02-02 22:26
@wmorrell Did I complain about the efforts of the existing volunteers? I did not intend to as I appreciate the effort really a lot.

"Money are not the problem", many users using vimperator, growing technical debt due to lack of programmers: this is not fault of existing volunteers at all. To me it is a sign of lack of structure in processes and organization as energy (money, demand) exist but do not flow well enough where required. Trying to think forward I feel, there is a need for a lead (or two), who could help the great solution to evolve.

I did not want to offend anyone. I just tried to contribute to a solution, I love so much (btw: is there some better place to discuss such things?).

My fingers are tapping the thanksgiving song many times a day: **Vimperator is my daily tool with that my browsing can fly at speed of thought, thanks all the contributors and I wish all of us: Live long and prosper, dear Vimperator.**

**Comment by wmorrell** [comment] 2017-02-02 22:58
@vlcinsky The more egregious complaining is further up-thread. Your comments are not of the same degree or severity, and I appreciate and believe that you are not intending to complain. It is just not helpful to comment along the lines of, "why is there no-one doing X?" especially if it's immediately followed by, "I won't do it." That reads as entitlement to the time and effort of the existing volunteers working on what you want.

I intend to make a weekend afternoon project to learn more about WebExtensions APIs. It won't get Vimperator ready for the final deprecation of XUL in Firefox 57, but it is a step in the right direction.

**Comment by blueyed** [comment] 2017-02-02 22:59
I think we should lock this issue, and rather create a new one for discussions.

From my point of view a lot of people (and especially developers) are using OSS, but do not contribute back: if you find an issue, please consider digging into the source!  That's not easy for all projects (e.g. Vimperator), but you should be able to create a local build, find the place to hack and then investigate.  And if you stumble while doing so, please at least create a PR for better docs while you find out something.

(I am maintaining some Vim plugins, and it is really discouraging if e.g. Python developers using jedi-vim are creating duplicate issues, instead of figuring out what is wrong, and then submit a small PR to fix it (although the problem is in the Python code))

Therefore it's not really money that's the issue, but rather to make development/hacking easy (docs!), and that users (especially developers) are willing to contribute back.

**Comment by timss** [comment] 2017-02-02 23:14
Good idea, @blueyed. We don't want to end up in [nikolas/github-drama](https://github.com/nikolas/github-drama/)! :p

There are some valid points that are brought up here, but should be done in a constructive manner in a seperate issue. I have some ideas how that could be done, so sit tight until I've made such an issue. In addition, lets all recognize that we want the same thing, and try to avoid fruitless discussion(s).

**Comment by gkatsev** [comment] 2017-02-17 22:41
Vimperator 3.16.0 has been officially approved. They did note two things that need to be looked at for an upcoming release. I'll open a new issue for those.

**Comment by gkatsev** [comment] 2017-02-17 22:58
Also, thanks to everyone who made this release possible!
