### ISSUE TITLE
vimperator mostly non-functional with firefox 51.0

### ISSUE THREAD

**Issue by waclena** [vimperator/vimperator-labs#689] opened 2017-02-03 20:06 UTC
##### Issue type:

- Bug report

##### Version:
Arch Linux firefox 51.0.1-1; fresh profile, no .vimperator dir nor .vimperatorrc.
```
Vimperator:     3.15.0 (created: 2016/10/05 01:11:26)
Firefox:        Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Vimperator barely works: only one tab* command listed at : prompt (tabgroups); t is mapped to tabopen but yields error "not a vimperator command".

On startup firefox says:

```
liberator: Error loading script tabs.js: SyntaxError: non-generator method definitions may not contain yield
```

##### Expected behavior:
tabs to open, etc.

##### Steps to reproduce:

Install firefox 51 and start it up.

**Comment by phi-gamma** [comment] 2017-02-03 20:10
Another dupe of #568

**Comment by SammysHP** [comment] 2017-02-03 22:30
This was fixed in the latest release.

**Closed by SammysHP** 2017-02-03 22:30 UTC

**Comment by spectromas** [comment] 2017-02-09 13:35
Do you know when this is going to be available?

**Comment by SammysHP** [comment] 2017-02-09 13:36
No. That's Mozilla's decision.
