### ISSUE TITLE
`d` should not close the browser if used on the last remaining tab

### ISSUE THREAD

**Issue by RomanHargrave** [vimperator/vimperator-labs#331] opened 2015-11-16 16:38 UTC
Prior to some unknown update (I didn't take much notice of this at first), using `d` (`:bd` hotkey) with one tab open would open a new tab at `about:blank` and close the previous tab, now it simply exits the window or browser, depending on how many windows are open.

This is _extremely_ inconvenient for me to work around, and there should be some option to disable this behaviour.

**Comment by franklinchou** [comment] 2015-11-16 18:36
Just to confirm; what version of vimperator/firefox are you using? I'm on Vimperator 3.10.1 with Firefox 42. Pressing `d` even with only one window and one tab open will __not__ close the browser. A new tab at `about:blank` will be opened.

**Comment by RomanHargrave** [comment] 2015-11-16 19:25
I am using 3.10.1 in Firefox Beta 43.0b3. It's safe to say that this has been an ongoing issue in 43.

**Comment by ratijas** [comment] 2015-11-17 00:59
same behavior — closing window on closing last tab — beging after upgrade to firefox 42 on Mac.  i'm using latest vimperator commit.

**Comment by shuei72** [comment] 2015-11-17 10:20
The behavior is not caused by Vimperator. It is only to change firefox config.
`about:config > browser.tabs.closeWindowWithLastTab > false (default:true)`
In Vimperator:
`:set! browser.tabs.closeWindowWithLastTab=false`

**Comment by ratijas** [comment] 2015-11-17 14:33
so, mozilla changed it…

@shuei72, your solution is somehow works, but it still not identical to what we had on 41.  before it was like switch to `about:blank` on `d` and closing window on `<M-W>`.  now it switching to `about:blank` both ways.

maybe we have to
```viml
:set! browser.tabs.closeWindowWithLastTab=false
map <M-w> :q<CR>
```, at least it works.

**Comment by RomanHargrave** [comment] 2015-11-18 15:08
@shuei72 good find. that's a silly behavioral change on mozilla's part. I would rather close the browse using the dedicated closing mechanic than the remaining tab.

**Comment by maxauthority** [comment] 2015-11-22 19:50
As a workaround, you can also put an about:blank tab and pin it (which
shouldn't be deleted with 'd' iirc, or was this also changed?). But yeah, I
don't like closing the window with just 'd' myself, it was made the same as
Firefox by popular demand.

**Comment by gkatsev** [comment] 2016-01-27 06:06
Closing since there's an option here.

**Closed by gkatsev** 2016-01-27 06:06 UTC
