### ISSUE TITLE
Support for Firefox 57/Electrolysis/Quantum/QuantumDevEdition

### ISSUE THREAD

**Issue by lweberk** [vimperator/vimperator-labs#792] opened 2017-09-28 14:48 UTC
##### Issue type:

Version compatibility

##### Versions:

- Firefox >= 57.0 (as of writing beta3)
- Firefox Quantum (alias)
- Firefox Quantum Developer Edition (alias)

##### Description:

Currently not supported. Mozilla is doing substantial changes to its Firefox extensions internals. As such there is much that would need to change for Vimperator to support this newer generations of Firefox.

##### References:

- #705 - Port to WebExtension   (the name for the new extensions development framework, somewhat aimed at supporting extensions in a browser-portable (chrome/ie/...) way)
- #729 - Feature wishlist for WebExtensions port  (users wish list to draw a map of the features that would be missed most without vimperator, so portability of each may be checked)

**Comment by lweberk** [comment] 2017-09-28 14:51
Sorry about the botchered inital creation... wrong button.

**Comment by jklai** [comment] 2017-09-28 18:34
There's been discussion on this in the past (rewrite parts of vimperator for WebExtensions, aka Firefox 57, aka Firefox Quantum), but many of the discussions have fizzled out. Whether work is still being done by the vimperator team in the background is unclear. That being said, there are alternatives that will be ready by the time Firefox 57 hits stable, but as most of us here knows... they are not nearly as powerful as vimperator/pentadactyl

https://github.com/vimperator/vimperator-labs/issues/705
https://github.com/vimperator/vimperator-labs/issues/729

**Comment by jvican** [comment] 2017-09-28 20:57
@lweberk This should be closed, it's a duplicated of #705

**Comment by lweberk** [comment] 2017-09-29 12:08
Not quite sure about that. It spent north of 10min scourging any issue hinting to support of FF57/Quantum... if no title seems to point me as non-extension-developer to the correct and already existing issue (WebExtension was a new word for me), there is the possibility for this issue to be a pointer for someone else too.

Instead of closing, I am going to double down on that rationale.

**Comment by lweberk** [comment] 2017-09-29 12:20
What is the earliest version of FF that introduces this quandry? WebExtensions was introduced in FF55, mandatory since FF57?

**Comment by SammysHP** [comment] 2017-09-30 18:08
Quantum is just a marketing name for the next release which drops support for old extensions and introduces some architectural changes (which speeds up everything a little bit). Closing because duplicate of #705.

**Closed by SammysHP** 2017-09-30 18:08 UTC
