### ISSUE TITLE
Invalid Parameters: t b a S and some keys not working in Firefox 51.0.1

### ISSUE THREAD

**Issue by Cutuchiqueno** [vimperator/vimperator-labs#680] opened 2017-02-01 10:18 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

After update to Firefox 51.0.1 I immediately get the error message: Invalid Paramters: t b a S
Some keys like gt, gT, d among others are not working, some like o, t … are working
Downgrading to Firefox 50.1.0 solve the problem
No configuration changes had been made in between

##### Expected behavior:

no error message, all the keybindings should work

**Comment by timss** [comment] 2017-02-01 10:58
Thanks for reporting this issue, but this seems to be a duplicate of #568 and was fixed in #675, ultimately released as [Vimperator 3.16](https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.16.0). New version coming on [AMO](https://addons.mozilla.org/en-US/firefox/addon/vimperator/) soon™.

If this is another issue and you've verified that the new release did indeed not resolve your problem, I'll reopen this issue.

**Closed by timss** 2017-02-01 10:58 UTC
