### ISSUE TITLE
Problems after updating to Firefox 56

### ISSUE THREAD

**Issue by geg-mopo3** [vimperator/vimperator-labs#795] opened 2017-10-03 09:51 UTC
##### Issue type:

- Bug report

##### Version:

```
3.16.0
```

##### Description:

I've noticed 2 issues so far:
1) After pressing the 'f' key the field for entering the search string will be displayed. The link numbers won't be shown.
2) Smart completions list has a transparent background so it's hard to differ between suggestions and the web site contents.

![default](https://user-images.githubusercontent.com/19689372/31119612-3a04c396-a83a-11e7-9275-4f600bcab84e.png)

##### Steps to reproduce:

1) Update to Firefox 56
2) Hit the 'f' key

**Comment by jcshelby** [comment] 2017-10-03 12:10
I'm having similar issues following the upgrade

**Comment by steils** [comment] 2017-10-03 12:18
Isn't it a duplicate of #777?

**Comment by geg-mopo3** [comment] 2017-10-03 12:23
@steils Yes and no. Yes to transparency in smart completions (I noticed a duplicate after I've posted it) and no to 'f' key command.

**Comment by SammysHP** [comment] 2017-10-03 17:58
Duplicate of #777 and #786.

**Closed by SammysHP** 2017-10-03 17:58 UTC

**Comment by andre-cunha** [comment] 2017-10-04 09:11
Confirmed bugs:

1) Transparent background when pressing "o" and "t"
2) Hint mode (f) presents search mode
3) search mode prints out "pattern not found" over the search term.

**Comment by JinhaoPro** [comment] 2017-10-12 09:10
same problem.
