### ISSUE TITLE
Follow hints does not mark any links

### ISSUE THREAD

**Issue by acken** [vimperator/vimperator-labs#697] opened 2017-02-06 09:39 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator: 3.15
Firefox 5 / 51
```

##### Description:

After doing a apt upgrade in ubuntu I got a new version of firefox and now when I hit f not links are marked.

Apparently copy the version did not work either.

##### Expected behavior:

Expects that links are marked and I can navigate to them

**Comment by timss** [comment] 2017-02-06 09:46
Thanks for reporting this issue, but this seems to be a duplicate of #568 and was fixed in #675, ultimately released as [Vimperator 3.16](https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.16.0). New version coming on [AMO](https://addons.mozilla.org/en-US/firefox/addon/vimperator/) soon™.

**Closed by timss** 2017-02-06 09:46 UTC
