### ISSUE TITLE
tabopen not working, link numbers not showing up

### ISSUE THREAD

**Issue by mimooh** [vimperator/vimperator-labs#674] opened 2017-01-28 23:11 UTC
- Bug report
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

Somethin's wrong. Somethin's not quite right. I've used it for years, but just today I noticed strange behaviour (perhaps due to autoupdate of either firefox or vimperator). Suddenly :tabopen results in "Not a vimperator command: tabopen". Also f displays "Follow link" but my html content doesn't get tagged with numbers at all! Looks like fundamentaly broken behaviour. On the other end, hjkl work, gh works, :open works. I haven't inspect stuff deeper, as this should be sufficient for this report. I reinstalled vimperator, restarted ff and the behaviour is still simply broken.

**Comment by wridgers** [comment] 2017-01-28 23:17
See https://github.com/vimperator/vimperator-labs/issues/568

**Comment by HadziJo** [comment] 2017-01-29 03:50
@minooh I believe this is directly related to Firefox release 51.0.1 
@wridgers #568 refers to FF beta and e10s, do you know if rel 51.0.1 contains the same code as the beta?

**Comment by pintjuk** [comment] 2017-01-29 15:58
I have the same problem with 51.0.1 (32-bit) on windows

**Comment by oliverralbertini** [comment] 2017-01-29 19:05
Same problem on arch linux using 51.0.1 (concerning tabopen) and I can also report that 'd' to close a tab doesn't work. 'd' fails silently, however.

**Comment by tskardal** [comment] 2017-01-29 19:13
..and same on macOS

**Comment by hshin23** [comment] 2017-01-29 20:32
'r' to refresh tab does not work.

**Comment by bheinzerling** [comment] 2017-01-29 22:18
There's a fix which seems to be in the process of getting approved. If you're like me and don't want to wait, you can install the fixed version like this: 

git clone https://github.com/ma8ma/vimperator-labs.git
cd vimperator-labs
git checkout update-generator-function
make xpi
then install xpi in the Firefox Addon screen

**Comment by hshin23** [comment] 2017-01-29 23:48
@bheinzerling 
Firefox shows that the addon is unsigned, and going through **about:config** to set the **xpinstall.signatures.required** to false is not resolving that.

**Comment by JarrodHenry** [comment] 2017-01-30 00:17
@hshin23 That about:config setting is ignored in non-nightly or non-developer versions of firefox.

**Comment by TimorLee** [comment] 2017-01-30 01:00
Also "b" for showing the buffer doesn't work (also Arch Linux here).

**Comment by 0re5ama** [comment] 2017-01-30 02:57
@bheinzerling 
I am on windows, and using GNU make in the repository gives the following error.
`File not found - *.css`
`make: *** [xpi] Error 2`

**Comment by fakedrake** [comment] 2017-01-30 03:38
How long before these things usually get approved?

**Comment by akarl** [comment] 2017-01-30 11:28
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0

- No hints for f, F
- ; No completions
- r, [[, ]] give Reference error: tabs is not defined
- d, b, gt and similar are just ignored
- t, T: Not a vimperator command

Vimperator became almost unusable. Would be great to get an fixed version soon.

**Comment by spellingmistake** [comment] 2017-01-30 19:02
@hshin23  Firefox ESR still supports disabling mandatory xpi signatures using _xpinstall.signatures.required_
@bheinzerling c76a292 does in fact solve this issue which is duplicate of #568. Out of curiosity, since #568 has been opened half a year ago, why was it only fixed tomorrow (judging from the CommitDate)? (Don't get this as criticism, it's just a question)

**Comment by JarrodHenry** [comment] 2017-01-31 03:07
I'm actually beginning to wonder if this is going to get fixed.  Are there alternatives to vimperator out there on firefox currently?

**Comment by hshin23** [comment] 2017-01-31 03:12
@JarrodHenry
Vimperator 3.15.0 on firefox-nightly (version 54 I believe) is not working at all. All I see is the bottom bar and none of the commands work. I might have done something wrong though.

@spellingmistake
I will try out firefox-esr.

**Comment by nschley** [comment] 2017-01-31 03:58
@JarrodHenry - you get what you pay for....   I wish I was able to contribute, but I gotta suffer through other folks getting through the issues, too.  

I'd migrated from vimperator to pentadactyl for a year or two -- very similar functionality -- however, the updates on that project started to get few & far between, so I returned here, (which had been great in terms of stability & reliability up to the issue of recent days.)

<2¢>I suggest either developing a sense of patience, or leveraging your sense of urgency and drive yourself to get involved in the project.</2¢>

**Comment by JarrodHenry** [comment] 2017-01-31 04:24
@nschley I already am involved in plenty of open source projects, and donate large amounts of money to many of them.   The main concern I have is that this issue is not just a few days old, it was identified nearly a half-year ago and was basically ignored, and now a commit has sat ready to go and I've seen very few of the core-devs talking about this here.  

Firefox is going through a lot of changes re: Quantum and this will not be the only time things break, and while I like the functionality, I can't have a non-working browser every few days, especially from regressions that are 6 months old.  

If Vimperator wanted donations, they could tell us how to pay them, so we could "get what we pay for"

**Comment by dusanx** [comment] 2017-01-31 08:50
e10s requires a lot of changes for vimperator code to work properly. ma8ma patch is temporary fix (thanks ma8ma) but it won't fix things for long. When using FF 51.0.1 then look at the about:support, vimperator prevents 'Multiprocess Windows' (e10s) from working.
It is strategic question if vimperator team can pull it off and really rewrite the code (and tell us how we can help in the process) or we must start looking elsewhere.
As a temporary solution I am using inox (https://bbs.archlinux.org/viewtopic.php?id=198763) and cvim (https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh). It kind of works with some tweaking, at least for basic navigation I need. Of course I would very much prefer to get back to firefox and vimperator, if possible at all.

**Comment by timss** [comment] 2017-01-31 10:03
Closing this issue as of #675. Please see [my comment](https://github.com/vimperator/vimperator-labs/pull/675#issuecomment-276303232) in the topic.

>Out of curiosity, since #568 has been opened half a year ago, why was it only fixed tomorrow (judging from the CommitDate)? (Don't get this as criticism, it's just a question)
– @spellingmistake 

The most obvious reason would be less exposure, even though addons such as Vimperator has quite a few of its users on the nightly or beta release channels. If a fix (PR) was issued earlier, maybe it could've been picked up before it was broken in stable.

> suggest either developing a sense of patience, or leveraging your sense of urgency and drive yourself to get involved in the project.
– @nschley 

This is what happened for me over time, :+1: 

>If Vimperator wanted donations, they could tell us how to pay them, so we could "get what we pay for"
– @JarrodHenry 

To be very clear (not just towards your comment); Vimperator needs code contributions, it's not a question of compensation for current/old maintainers.

>e10s requires a lot of changes for vimperator code to work properly. ma8ma patch is temporary fix 
– @dusanx 

Please use #211 for discussing e10s.

**Closed by timss** 2017-01-31 10:03 UTC
Labels: compatibility

**Comment by hshin23** [comment] 2017-02-01 05:09
@JarrodHenry You could check out [qutebrowser](https://github.com/The-Compiler/qutebrowser)
