### ISSUE TITLE
Can't change colourscheme, firefox error returned

### ISSUE THREAD

**Issue by hosalmeer** [vimperator/vimperator-labs#810] opened 2017-11-03 18:14 UTC
##### Issue type:

- Bug report

Colourscheme can't be changed

##### Version:

```

```Version Information
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

##### Description:



Tried to change colorscheme. Same issue with zenburn, ywgx, and molokai. No colour change and the following message in the bar

[Exception... "Component returned failure code: 0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL)
[nsIStuleSheetService.loadAndRegisterSheet]"

##### Expected behavior:

New coloourscheme, obviously. 

##### Steps to reproduce:

<!-- Include if relevant -->

**Comment by SammysHP** [comment] 2017-11-03 20:30
Duplicate of #796.

**Closed by SammysHP** 2017-11-03 20:30 UTC
