### ISSUE TITLE
Firefox 44 breaks vimperator

### ISSUE THREAD

**Issue by johntyree** [vimperator/vimperator-labs#378] opened 2016-01-27 02:34 UTC
I only had it installed for a few minutes before I panicked and reverted to 43, but I noticed at least the following on 44.0.

- Every command causes a `SyntaxError: attr2` error message
- Hints do not show up at all
- The location bar does not hide

**Comment by gkatsev** [comment] 2016-01-27 02:37
Thanks. This is a dupe of #352.

**Closed by gkatsev** 2016-01-27 02:37 UTC

**Comment by johntyree** [comment] 2016-01-27 02:38
Oh, Sorry. I assumed this would be new, of course people have been testing nightlies and so the issue is old by now. My fault. :)

**Comment by gkatsev** [comment] 2016-01-27 02:44
Heh, no worries. I've updated the issue title so hopefully it'll be easier to find.
