### ISSUE TITLE
vimp doesn't respect FF's browser.tabs.selectOwnerOnClose

### ISSUE THREAD

**Issue by LeLobster** [vimperator/vimperator-labs#624] opened 2016-10-19 16:59 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
```

##### Description:

Best explained using an example:
When browsing reddit and opening a thread from the frontpage in a newtab, closing that tab would return to the reddit frontpage tab (it's owner)
When using vimperator, opening a thread by following the `hint` and then closing the tab by `d` or `:quit` it selects the tab after the closed tab instead of returning to the owner tab.

##### Expected behavior:

I'd expect it to return to the owner tab just like vanilla FF would because `browser.tabs.selectOwnerOnClose` is set to true.

**Comment by timss** [comment] 2016-10-24 07:35
Thank you for your bug report. This seems like a duplicate of #435, so I'm closing this one.

>d is defined as close the tab and go left. D is close the tab and go right.
We possibly would want an option to do the same behavior as <c-w> but the default shouldn't change as there are probably people relying on that behavior as well.

– gkatsev ([comment](https://github.com/vimperator/vimperator-labs/issues/435#issuecomment-191823295))

**Closed by timss** 2016-10-24 07:35 UTC
