### ISSUE TITLE
Can't remap <space>?

### ISSUE THREAD

**Issue by anoda9** [vimperator/vimperator-labs#270] opened 2015-08-26 18:52 UTC
It seems like vimperator can't remap the spacebar.
I put this in my rc file:
>nnore <Space> 24j
nnore <S-Space> 24k

and shift-space works fine, but space still keeps its default behavior.

**Comment by gkatsev** [comment] 2015-08-26 18:57
Duplicate of #10.

**Closed by gkatsev** 2015-08-26 18:57 UTC

**Comment by anoda9** [comment] 2015-08-26 19:05
Whoops. I searched issues for "remap space" before posting but nothing came up. :)

**Comment by gkatsev** [comment] 2015-08-26 19:09
no worries :)
