### ISSUE TITLE
Tabnumbers do not display 

### ISSUE THREAD

**Issue by franklinchou** [vimperator/vimperator-labs#311] opened 2015-10-17 20:52 UTC
The option `set tabnumbers` does not correctly display tabnumbers. Instead small gray boxes are displayed. This is possibly related to issue #116. Neither installing the developer theme nor restarting Firefox seems to correct this error.

![vimperator_1](https://cloud.githubusercontent.com/assets/4894646/10561242/755d5014-74ef-11e5-97e9-7be7654317a0.png)

Using:
-- vimperator version 3.10.1
-- firefox version 41.0.2 
-- Microsoft Windows, version 10.0.10240

**Comment by gkatsev** [comment] 2015-10-18 01:14
We've had a fix come in as #303. Closing as a duplicate of #274.
I'll see if I can get a prerelease out soon, but until then, either turn them off or build off of master.

**Closed by gkatsev** 2015-10-18 01:14 UTC
