### ISSUE TITLE
Firefox 46.0 breaks vimperator

### ISSUE THREAD

**Issue by alexconst** [vimperator/vimperator-labs#489] opened 2016-04-26 17:12 UTC
##### Issue type:

- Version compatibility

##### Version:

```
<!-- (Paste the output of `:version` here) -->
Impossible!
Latest Firefox 46.0 breaks vimperator. Plugin is no longer loaded.
On about:addons it says `3.12.0`
```

##### Description:

Vimperator plugin no longer loaded, despite being enabled.
Impossible to access <liberator://help/options>

Strangely enough in [firefox add ons page](https://addons.mozilla.org/en-US/firefox/addon/vimperator/contribute/roadblock/?src=search&version=3.12.0) I am still able to download it.
So maybe it's not being detected as installed? Despite `about:addons` saying otherwise.

##### Expected behavior:

For Firefox to stop breaking plugins.

##### Steps to reproduce:

Update to Firefox 46.0 in Linux amd64

**Comment by timss** [comment] 2016-04-26 17:18
Thanks for reporting, but this is a duplicate of #398. Closing.

**Closed by timss** 2016-04-26 17:18 UTC
