### ISSUE TITLE
gi broken in Firefox 35

### ISSUE THREAD

**Issue by nnkken** [vimperator/vimperator-labs#151] opened 2015-01-20 17:57 UTC
:version
Vimperator:	3.8.3 (created: 2014/11/09 13:19:01)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0

When I press "gi", I suppose vimperator to select the first input field of the webpage.
But in Firefox 35, what it do is to select the last selected input field, and if no input field has been selected, it will gives the following error:
TypeError: 'snapshotLength' getter called on an object that does not implement interface XPathResult.
(BTW, is there any quick way to copy the error message? I have to type it by myself...)

**Comment by nnkken** [comment] 2015-01-20 18:01
Sorry for not having tried for the latest development version on GitHub before submitting the issue.
It seems that the bug has gone in the newest development version.

**Comment by gkatsev** [comment] 2015-01-20 18:02
`:messages` might let you more able to select the message.
Also, this is a dupe of #33.

**Comment by gkatsev** [comment] 2015-01-20 18:02
Glad you found the latest release :)
No worries

**Closed by gkatsev** 2015-01-20 18:02 UTC
