### ISSUE TITLE
follow link is not working in debian 8, firefox 56.0 (64-bit), vimperator 3.16.0

### ISSUE THREAD

**Issue by pchaitat** [vimperator/vimperator-labs#794] opened 2017-10-01 03:57 UTC
##### Issue type:

- Bug report

##### Version:

```
Version Information
  Vimperator: 3.16.0 (created: 2017/02/01 00:55:15)
  Firefox: Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
```

##### Description:

Just few days ago, I noticed the issue.  At least, "f" (follow link), "b" command to switch to a tab and ":help" don't work anymore.  But some commands such as, "t" to open a new tab and "d" to close a tab still work.

Right now, when I enter "f", it behaves as if I issue a "find text" command.  It waits for string to be entered.  Once entered, it tries to search for that string on the current webpage.

##### Expected behavior:

When I enter "f", it should show the numbers on each link on any web page.  When I enter "b", it should show the list of active tabs.  When I enter ":help", it should show the Vimperator help page.

**Comment by SammysHP** [comment] 2017-10-01 18:35
Duplicate of #786.

**Closed by SammysHP** 2017-10-01 18:35 UTC
