### ISSUE TITLE
imap / inoremap definitions not loaded from _vimperatorrc

### ISSUE THREAD

**Issue by tosts** [vimperator/vimperator-labs#136] opened 2015-01-10 17:20 UTC
Windows 8.1 Pro
vimperator 3.8.3
firefox 34.0.5

_vimperatorrc (generated via `:mkv`):
```VimL
"3.8.3 (created: 2014/11/09 13:19:01)

cnoremap jk <Esc>
inoremap jk <Esc>
nnoremap j 8j
nnoremap k 8k
noremap <C-h> gT
noremap <C-l> gt
source! "C:\\Users\\XXXX\\_vimperatorrc.local"

" vim: set ft=vimperator:
```

After starting firefox i can see the command mode mapping via `:cmap`, the other mappings via `nmap` but the insert mode mapping is neither visible nor working.
Tried writing as `imap` as well, didn't work either.
Anyone can confirm?

**Comment by tosts** [comment] 2015-01-10 19:04
Adapting https://gist.github.com/anekos/3237219 for `mode.INSERT` accordingly works.
Mapping is then also visible with `:imap`

**Comment by timss** [comment] 2016-02-29 23:17
Sorry this was never picked up, but the isse seems very out of date at this point and since I'm not able to reproduce it I'm going to close the issue.

If you or anyone else is still experiencing this issue, please tell and it'll be reopened.

**Closed by timss** 2016-02-29 23:17 UTC
