### ISSUE TITLE
Firefox's native search bar appear when press n/N if pattern is not found

### ISSUE THREAD

**Issue by antiquity** [vimperator/vimperator-labs#466] opened 2016-03-21 16:43 UTC
##### Issue type:
- Bug report

##### Version:

```
Vimperator:	3.12.0 (created: 2016/02/28 22:07:56)
Firefox:	Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

After using '/' or '?' to search some string that is not found in the page, press n/N will bring up the firefox's native search bar.

##### Expected behavior:

Just keep showing "Pattern not found: xxxx"

**Comment by timss** [comment] 2016-03-22 08:11
Thank you for reporting this issue, however I'm closing this as a duplicate of #453. 

For now, please follow the master branch using a [development installation](https://github.com/vimperator/vimperator-labs/blob/master/CONTRIBUTING.md#development-installation) or compiling it yourself so you can get #443 in your clone of Vimperator.

**Closed by timss** 2016-03-22 08:11 UTC
