### ISSUE TITLE
`n`ext match pops up Find Bar if no matches found

### ISSUE THREAD

**Issue by wisq-minted** [vimperator/vimperator-labs#478] opened 2016-04-07 14:46 UTC
##### Issue type:

- Bug report

##### Version:

Err … I can't copy the data from `:version`, neither by highlighting it nor by "Y"anking it.  I guess I should report that as a separate bug?  In any case, it's 3.12.0:

![vimperator-labs - vimperator-20160407-103252](https://cloud.githubusercontent.com/assets/10052322/14355033/9e148b12-fcad-11e5-820c-f9bd4300d1a6.jpg)

##### Description:

If I press `n` to jump to the next match for my previous `/` find command, and there are no matches on the page, Firefox's Find Bar pops up.

My cursor is now in the search field in the Find Bar, so all further keypresses go there.  I have to hit escape to resume normal Vimperator activity, and even then, the Find Bar doesn't go away; I have to close it manually with my mouse.

##### Expected behavior:

I would expect to just get a beep and an error message on the status line, same as if a `/` find failed to find anything.  I'm pretty sure this used to be the standard Vimperator behaviour in this case.

##### Steps to reproduce:

1. press `/`
2. type in a gibberish search that doesn't show up on the page, hit enter
3. press `n` — find bar pops up

Tested with my `.vimperatorrc` renamed to ensure it's not something I've done.

**Comment by boba1l0s2k9** [comment] 2016-04-10 06:13
Yes what you expect was standard behavior until very recently, it's either an interplay with Firefox 45 (or another recently updated add-on?) or regression in Vimperator (I have the same issue, just started within the last week).

**Comment by foxxx0** [comment] 2016-04-10 13:38
Same issue here for ~1 week already, I guess it's caused by the new Firefox version.

**Comment by benoit-pierre** [comment] 2016-04-13 14:21
Possible workaround with Stylish:

```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

findbar	{
  display: none;
}
```

**Comment by timss** [comment] 2016-04-13 20:36
@benoit-pierre Thanks for posting.

CSS rules can be defined using `style`, so no need for Stylish though.

**Comment by benoit-pierre** [comment] 2016-04-13 20:53
@timss: right! Forgot about that... So:

`style -name=nofindbar chrome://* findbar { display: none; }`

**Comment by timss** [comment] 2016-05-02 16:24
Not able to reproduce with FF 45 and latest build (e8eade2) using a clean profile. 

Can anyone else confirm or reproduce?

**Comment by benoit-pierre** [comment] 2016-05-02 16:48
I can't with FF 46 and Vimperator 3.13.0, so it looks like it has indeed been fixed.

**Comment by timss** [comment] 2016-05-02 16:57
Great, thanks for testing! 

Closing.

**Closed by timss** 2016-05-02 16:57 UTC
