### ISSUE TITLE
Vimperator does not work in Firefox 44

### ISSUE THREAD

**Issue by AppleDash** [vimperator/vimperator-labs#352] opened 2015-12-17 00:21 UTC
I just installed Vimperator, and its behaviour is very buggy to me.

After every command I run, the status bar turns red and outputs "SyntaxError: attr2". Some commands work, some don't.

When doing `:help`, it outputs something along the lines of "Sorry, help file undefined", but it goes away so quickly that I can barely read half of it.

**Comment by gregist** [comment] 2015-12-21 04:44
I can confirm this on 44.0b1, please fix.

**Comment by j127** [comment] 2015-12-21 23:50
Vimperator doesn't work for me any more on 43.0 (Ubuntu 14.04). I don't see anything in the browser console when I press keys like `o`, `t`, and `w`. Nothing happens when those keys are pressed. I'm not sure how to debug the problem.

**Comment by reepush** [comment] 2015-12-22 06:35
@gregist Try to build from `master`:
```
git clone https://github.com/vimperator/vimperator-labs.git
cd vimperator-labs && make
```

Then install _downloads/vimperator-3.10.1.xpi_.
I have tried it on Firefox 44. Most of the commands worked, but textarea had strange behavior.

**Comment by gregist** [comment] 2015-12-22 11:20
@reepush It worked. Thanks!

It appeared that I updated my local git last time but forgot to install the latest xpi...

**Comment by craftyguy** [comment] 2015-12-22 19:16
Worked for me as well.. hopefully the maintainers publish an "official" release soon based on the latest commits that seem to resolve the biggest issues with using vimperator on FF 44...

**Comment by timss** [comment] 2016-01-26 18:20
@gkatsev Firefox 44 were officially released today. A new release is needed on GH and AMO for those who can't/won't compile it themselves.

https://www.mozilla.org/en-US/firefox/44.0/releasenotes/

**Comment by gkatsev** [comment] 2016-01-26 18:29
@timss thanks for reminding me. Going to look at it tonight.

**Comment by Roguelazer** [comment] 2016-01-26 21:36
+1 that it's much better with git HEAD.

**Comment by gkatsev** [comment] 2016-01-27 04:41
I've tagged what's available as 3.11 and released it on github and uploaded to AMO.
If you're using aurora, you can grab the XPI from github and install it by disabling `xpinstall.signatures.required` to `false`. Others will need to wait for mozilla to approve the addon. It can take a couple of days.
Since it's released, I'm going to close this issue. If there are particular issues that pop-up afterwards, we should open individual issues for each. Thanks for everyone who helped make this release happen!

**Closed by gkatsev** 2016-01-27 04:41 UTC

**Comment by wallydrag** [comment] 2016-01-28 05:33
@reepush big thanks for the solution, although have you had any luck with the text area section?

**Comment by reepush** [comment] 2016-01-28 08:03
@wallydrag not yet, still on the way to contribute to vimperator :)

**Comment by xubin990510** [comment] 2016-02-03 11:48
also noticed that on start it says `array(...).flatten is not a function`

**Comment by rr-** [comment] 2016-02-06 16:50
When can we hope to get a release with 9b6eda8ad6a0eac4d8bff6bd6ee39d9ff53ec741?
