### ISSUE TITLE
Calling external editor from within Github.com text fields

### ISSUE THREAD

**Issue by tecfu** [vimperator/vimperator-labs#528] opened 2016-06-03 20:25 UTC
#####_ Issue type:

- Bug report

##### Version:
```
Vimperator:	3.13.1 (created: 2016/05/04 01:34:00)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
```

##### Description:

When using the Vimperator to navigate the Github.com website, I'd like to be able to use the <C-i> keybinding to open an external editor, as discussed here: http://superuser.com/questions/376045/vimperator-is-there-any-way-to-edit-text

In most sites, `<C-i>` works. But in some others, like Github,  it does not. Instead, when I press `<C-i>` I receive the following output:

__

So it appears that Github has this key combination bound. 

Issue:

1. How can this be overridden? 
2. What's the command in Vimperator to open an external editor while in a focused text field?

##### Expected behavior:

gVim opens and allows editing of fields..

**Comment by tecfu** [comment] 2016-06-03 20:33
Please note that I found the following discussion on stackoverflow.com that discusses a workaround via rebinding <C-i> to <leader>i. 

I think it would also be really helpful if a command could be executed in command mode that opened an editor on the last focused field.

**Comment by gkatsev** [comment] 2016-06-03 20:41
This is a duplicate of #34, closing.

**Closed by gkatsev** 2016-06-03 20:41 UTC
