### ISSUE TITLE
Cant escape from insert mode on Quora

### ISSUE THREAD

**Issue by ghost** [vimperator/vimperator-labs#46] opened 2014-10-01 13:37 UTC
on Quora.com as soon as the page loads the search field is selected and vimperator is in insert mode
hitting escape has no effect , and insert mode can only be escaped by clicking somewhere .

**Comment by maxauthority** [comment] 2015-01-21 19:47
Has anyone tried the patch from @severtsev to see if it causes some other weird problems? Patches at that low level are always risky and needs some testing.

**Comment by gkatsev** [comment] 2015-01-21 20:13
@severtsev care to submit a PR for your change? It'll be easier to check out.

**Comment by severtsev** [comment] 2015-01-21 22:35
@gkatsev #154

**Comment by caisui** [comment] 2015-01-23 12:37
This issue is caused by bug 501496.

see:
https://developer.mozilla.org/en/Firefox/Releases/25#Interfaces.2FAPIs.2FDOM
https://bugzilla.mozilla.org/show_bug.cgi?id=501496


simplistic fix
```diff
diff --git a/common/content/events.js b/common/content/events.js
index 285a1e9..7731ad6 100644
--- a/common/content/events.js
+++ b/common/content/events.js
@@ -1083,7 +1083,7 @@ const Events = Module("events", {
 
     // this is need for sites like msn.com which focus the input field on keydown
     onKeyUpOrDown: function (event) {
-        if (modes.passNextKey || modes.passAllKeys || modes.isMenuShown || Events.isInputElemFocused())
+        if (modes.passNextKey || modes.passAllKeys || modes.isMenuShown)
             return;
         event.stopPropagation();
     },
```

I think that it is necessary to implement the command, such as `ignorekeys` command.

example:
`
:stoppropagation add play\\.google\\.com
`


--

about: #28 

select element's keydown event has been implemented in native code....
http://mxr.mozilla.org/mozilla-central/source/layout/forms/nsListControlFrame.cpp#2177

**Comment by gkatsev** [comment] 2015-01-23 17:17
@caisui unfortunately, that simplistic fix isn't going to fly. That was the exact issue that brought on #90 where content-editable divs weren't considered input elements, so, the event propagation was stopped on them and caused a whole lot of issues.

**Comment by caisui** [comment] 2015-01-24 04:13
>  the event propagation was stopped on them and caused a whole lot of issues.

Yes, so that it is necessary to implement a blacklist (or white list) in order to control propagation.
It is the above-mentioned `stoppropagation` command.

```diff
diff --git a/common/content/events.js b/common/content/events.js
index 1669478..89bec77 100644
--- a/common/content/events.js
+++ b/common/content/events.js
@@ -1083,7 +1083,7 @@ const Events = Module("events", {
 
     // this is need for sites like msn.com which focus the input field on keydown
     onKeyUpOrDown: function (event) {
-        if (modes.passNextKey || modes.passAllKeys || modes.isMenuShown || Events.isInputElemFocused())
+        if (modes.passNextKey || modes.passAllKeys || modes.isMenuShown || (Events.isInputElemFocused() && CheckPropagation(xxx))
             return;
         event.stopPropagation();
     },
```

**Comment by maxauthority** [comment] 2015-02-26 21:23
Does Commit #154 fix it? Then we can close the issue.

**Comment by gkatsev** [comment] 2015-02-26 21:53
Going to close this since #154 landed in master. I'll release a nightly on github when I get home tonight.
If we have issues with this, we could always re-open the issue.

**Comment by gkatsev** [comment] 2015-03-02 15:31
#154 was reverted. Reopening.

**Comment by derenio** [comment] 2015-03-31 11:04
I've just found out that **pressing `Ctrl+[` successfully escapes the `insert mode`** of input/textarea on the problematic pages (that is https://slack.com and http://quora.com in my case).

I was forced to "discover it" as some recent commits* since the "revert of #154" made the "new message" input on slack auto-focused, not giving me even a single command before going `insert mode`).

* I suspect this one https://github.com/vimperator/vimperator-labs/commit/3a989ab5eb72b29585a3f6c17a2b2b3729a03775

**Comment by maxauthority** [comment] 2015-03-31 21:06
What do you mean with "revert of #154
<https://github.com/vimperator/vimperator-labs/pull/154>"? Shouldn't that
still be in master?
Or do you mean #154 causes the problems for you?

**Comment by derenio** [comment] 2015-04-01 08:21
I was basing my comment on the context of the previous comment, that is to:

`Revert "Merge pull request #154 from severtsev/master" as it causes #198` https://github.com/vimperator/vimperator-labs/commit/78b296ff04bb34049ebebbf544bb7f5577704b97

That was the last time (before yesterday) I've pulled the latest changes and made the plugin. Since the #154 was already reverted, this issue was (and is) still present.

Yesterday it got worse as the "message input" on `slack` is being auto-focused* (despite `set focuscontent`). I've just reverted the commit https://github.com/vimperator/vimperator-labs/commit/3a989ab5eb72b29585a3f6c17a2b2b3729a03775 and it worked (no focus) as before.

(*) Actually the `auto-focus` with `slack` wasn't the purpose for that comment. Before, I've managed to overcome this issue (#46) with tab's change (`alt+X`, `alt+Y` - as at start the input wasn't focused). Since this doesn't work anymore, I've discovered that the `Ctrl+[` successfully escapes, hence I wanted to share this workaround.

**Comment by tecfu** [comment] 2015-04-03 01:45
@derenio This works for me on Ubuntu 14.04 / Firefox 37. 

Great hack.

**Comment by maxauthority** [comment] 2015-04-06 20:15
Hmm, so the question is if we should revert 3a989ab
<https://github.com/vimperator/vimperator-labs/commit/3a989ab5eb72b29585a3f6c17a2b2b3729a03775>
as
well, as it seems to fix some issues, but also cause others :/ The question
is which causes MORE/more severe issues?

**Closed** 2015-09-05 10:30 UTC
