### ISSUE TITLE
Page reload does not work: "ReferenceError: tabs is not defined"

### ISSUE THREAD

**Issue by gn36** [vimperator/vimperator-labs#692] opened 2017-02-04 14:10 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Pushing "r" or typing ":reload" usually reloads the currently open page. Currently, an error is displayed instead:
```
ReferenceError: tabs is not defined
```
Starting Firefox with a new profile and then reinstalling vimperator does not solve this problem.

##### Expected behavior:

The page is reloaded.

##### Steps to reproduce:

- Load a random website.
- Push "r"
or
- Load a random website
- type ":reload"

**Comment by pldiiw** [comment] 2017-02-04 18:24
See #568.

**Comment by gkatsev** [comment] 2017-02-04 18:31
Dupe of #568. It's been fixed in master, just waiting on review.

**Closed by gkatsev** 2017-02-04 18:31 UTC

**Comment by pldiiw** [comment] 2017-02-04 18:37
This means that if you don't want to wait for the review to complete, you can just clone the repo and build the extension yourself, it works! :)
