### ISSUE TITLE
Firefox 49: open and tabopen do not offer website completions anymore

### ISSUE THREAD

**Issue by resetreboot** [vimperator/vimperator-labs#599] opened 2016-09-29 08:23 UTC
##### Issue type:

- Bug report

##### Version: 3.14.0

Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0

##### Description:

After updating Firefox to version 49, when I issue the commands :open or :tabopen the completion list appears empty. Checked entering urls at the address bar and FF offers completions (discarding I accidentally deleted navigation history). Search keywords appear correctly.

##### Expected behavior:

A list of recently and history stored sites to appear when I start entering the beginning of the URL.

**Comment by xsteadfastx** [comment] 2016-09-29 13:13
I can reproduce that.

**Comment by timss** [comment] 2016-09-29 13:46
Thanks for the report.

Closing as duplicate of #590, fixed in #591.

**Closed by timss** 2016-09-29 13:46 UTC
