### ISSUE TITLE
help page for `map`

### ISSUE THREAD

**Issue by ratijas** [vimperator/vimperator-labs#358] opened 2015-12-20 06:40 UTC
at `liberator://help/map#<Leader>`:

```
<Leader>
        
            Expands to the value of the "mapleader" variable in key mapping. If
            "mapleader" is unset or empty then \ is used. Example:
        
        :map h :echo "Hello"
        
works like
        :map \h :echo "Hello"
        
but after
        let mapleader = ","
        
it works like
        :map ,h :echo "Hello"
```

i guess in first example there was "`<Leader>`" which was removed by html parser.

**Comment by gkatsev** [comment] 2016-01-27 06:15
yeah, this is because out help files still use XML/XSLT. Going to close this as a duplicate of #73.

**Closed by gkatsev** 2016-01-27 06:15 UTC
