### ISSUE TITLE
Vimperator does not work

### ISSUE THREAD

**Issue by mitsugu** [vimperator/vimperator-labs#488] opened 2016-04-26 11:36 UTC
##### Issue type:
- Bug report

##### Version:
3.12.0

##### Description:
Vimperator does not work

##### Expected behavior:
Vimperator does work

##### Steps to reproduce:
1. Install Vimperator
2.Restart Firefox
3.Vimperator does not work

OS:Ubuntu Mate 16.04
Firefox:Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
Vimperator:3.12.0

**Comment by chiemseesurfer** [comment] 2016-04-26 12:45
I have the same issue after upgrading firefox to 46.0

**Comment by timss** [comment] 2016-04-26 15:01
"Does not work" isn't of much value. 

- What doesn't work?
- Any errors or output? 
- Is it the same as #456 or the related issues?

**Comment by chiemseesurfer** [comment] 2016-04-26 15:18
Does not work:
- does not accept any commands configured in .vimperratorc
- default commands like dd or f are not working any more
- I don't think it is related to #456 because there just a single command is not working and not the whole vimperator plugin itself...

**Comment by gkatsev** [comment] 2016-04-26 15:19
Unfortunately, vimperator doesn't work with firefox 46 right now :(. It's probably a duplicate of #398.
I'm going to be reviewing @reepush's PR today or tomorrow to get a release out this week.

**Closed by gkatsev** 2016-04-26 15:19 UTC
