### ISSUE TITLE
GitHub <C-i> not working

### ISSUE THREAD

**Issue by SammysHP** [vimperator/vimperator-labs#445] opened 2016-03-03 13:21 UTC
When pressing <kbd>ctrl</kbd>+<kbd>i</kbd> in insert mode on GitHub (e.g. comment textarea) the external editor is not invoked. Instead the GitHub editor command is executed (italic mode).

edit: Just found this comment: https://github.com/vimperator/vimperator-labs/issues/384#issuecomment-181253882

**Comment by timss** [comment] 2016-03-03 13:32
Thanks for reporting, but this is a duplicate of #34.

**Closed by timss** 2016-03-03 13:32 UTC
