### ISSUE TITLE
ignorekeys doesn't work on Firefox ESR 45.8

### ISSUE THREAD

**Issue by QuAzI** [vimperator/vimperator-labs#750] opened 2017-04-04 20:03 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

I install Firefox ESR 45.8 because Firefox 51+ (all versions with multiprocess support) too slow and require too many resources. Now all works fast but `ignorekeys add feedly.com` doesn't work.

**Comment by timss** [comment] 2017-04-09 12:05
Probably a duplicate of #722, see especially https://github.com/vimperator/vimperator-labs/issues/722#issuecomment-281429138. If you want to continue using FF45, you may have better luck with Vimperator 3.15 depending on your usage.

**Closed by timss** 2017-04-09 12:05 UTC

**Comment by SammysHP** [comment] 2017-04-09 16:19
And you can update to FF 52 ESR. There is no multiprocess enabled when you use most of the current addons.

**Comment by QuAzI** [comment] 2017-04-09 16:31
I don't know about multiprocess in 52 ESR but many errors and
performance lags exist. 45 ESR work better in any cases.
