### ISSUE TITLE
tabnumbers, gt don't work, inconsistent windows

### ISSUE THREAD

**Issue by amirkarger** [vimperator/vimperator-labs#710] opened 2017-02-10 02:04 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:     3.15.0 (created: 2016/10/05 01:11:26)
Firefox:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

I generally have several windows open with several tabs in each. I'm now experiencing several weird issues:

1. `:se tabnumbers` doesn't work. It's in my .vimperatorrc, and it used to work. But now on startup I get an error message that it's not a valid option. Also if I type `:se ta` and tab complete, it doesn't work. But tabnumbers is still mentioned in the docs
2. gt doesn't work
3. d stopped deleting tabs. (Weirdly, it seems like sometimes this problem happens in only one of my windows.) But t(abopen) still works, as does y(ank) etc.

I tried to  upgrade to the 2017-02-01 version of vimperator, by going to vimperator.org and downloading, which takes me to the addon page, asks for money, then says it will install after restart. I tried restarting immediately, or the "Not now" option and then going into about:addons and telling it to update. In both cases, after restart I still had the buggy behavior, and :version still reported the 2016-10 version. 

##### Expected behavior:

tabnumbers, gt, d to work again.

**Comment by apheleia** [comment] 2017-02-10 08:04
Vimperator 3.16, which is under review, will fix these issues for Firefox 51.

**Comment by Griffinhart** [comment] 2017-02-10 10:46
Related to/duplicate of #709, possibly.

**Comment by gkatsev** [comment] 2017-02-10 15:54
duplicate of #568

**Closed by gkatsev** 2017-02-10 15:54 UTC

**Comment by amirkarger** [comment] 2017-02-10 16:14
Thanks for the response. Glad to hear there's a fix coming.

The reason I got confused is that
https://raw.githubusercontent.com/vimperator/vimperator-labs/master/vimperator/NEWS
lists what looks like a 2017-02-01 release, AND it doesn't list the release
number as 3.16.0. The addons page lists the version 3.15.0, but doesn't
list the version date from 2016. I wonder if there's a way to update one or
both of these pages so it's more clear.
