### ISSUE TITLE
Sometimes I can't get away from insert mode. How can I force to leave from insert mode ?

### ISSUE THREAD

**Issue by MaikoID** [vimperator/vimperator-labs#163] opened 2015-01-30 15:27 UTC
Hey guys, there are site where I can't exit the insert mode without a mouse click in a blank area on the page.

100% reproducible 
www.quora.com
Google Sheets.

What can I do to force my way out from insert mode ?

BR

**Comment by timss** [comment] 2015-01-30 21:38
This can happen with ill behaving input fields and textareas. Not if this is Vimperator or a Firefox issue to be honest. 

A workaround that sometimes works though is to use 'tab' to select the next element where <kbd>Esc</kbd> or <kbd>Ctrl</kbd>+<kbd>c</kbd> might work. 

I can't test on quora or Google sheets myself because I use neither of the sites and have no interest in registering.

**Comment by gkatsev** [comment] 2015-01-30 21:40
This is a duplicate of #46.
It's a complicated issue and there's some possible solutions in that thread. It's definitely a vimperator issue but possible because of how firefox handles key events on some elements.

**Closed by gkatsev** 2015-01-30 21:40 UTC
