### ISSUE TITLE
d –  close the active tab (delete the buffer)   inactive

### ISSUE THREAD

**Issue by leemeng0x61** [vimperator/vimperator-labs#696] opened 2017-02-06 08:52 UTC
##### Bug report:
d –  close the active tab (delete the buffer)   inactive
also u inactive

##### Version:
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

vimoperator v 3.15.0

##### Description:

d –  close the active tab (delete the buffer)   inactive
also u inactive

**Comment by dschrempf** [comment] 2017-02-06 09:30
Please see #670.

**Comment by timss** [comment] 2017-02-06 09:47
Thanks for reporting this issue, but this seems to be a duplicate of #568 and was fixed in #675, ultimately released as [Vimperator 3.16](https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.16.0). New version coming on [AMO](https://addons.mozilla.org/en-US/firefox/addon/vimperator/) soon™.

**Closed by timss** 2017-02-06 09:47 UTC
