### ISSUE TITLE
findbar._setHighlightTimeout is not a function

### ISSUE THREAD

**Issue by cnfczn** [vimperator/vimperator-labs#716] opened 2017-02-12 15:01 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:
press / find anything in page

##### Expected behavior:
error message:
findbar._setHighlightTimeout is not a function

**Comment by SammysHP** [comment] 2017-02-12 17:56
Duplicate of #676.

**Closed by SammysHP** 2017-02-12 17:56 UTC
