### ISSUE TITLE
Favicon (site icons in search) are not resized correctly

### ISSUE THREAD

**Issue by axel-angel** [vimperator/vimperator-labs#805] opened 2017-10-17 06:58 UTC
##### Issue type:

- Bug report

##### Version:

```
Version Information
Vimperator:	3.16.0 (created: 2017/10/17 08:47:55)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
```

##### Description:

Since I updated to firefox 56 from 55, vimperator has huge favicons in the completion of websites with :open or :tab. It seems the favicon is displayed without resize because some sites like trello or youtube are HUGE and some are big like github. They are all displayed with their own size which makes the lines unreadable. See screenshots.

##### Expected behavior:

Works like before with firefox 55, favicons in completion should be resize. It was something like 32² px.

##### Steps to reproduce:

Upgrade to firefox 56. I tried with a vanially firefox without profile, I could reproduce the issue.

**Comment by axel-angel** [comment] 2017-10-17 06:59
Screenshots

![bug1](https://user-images.githubusercontent.com/2393097/31650832-7674fd7a-b319-11e7-8282-725854c388b9.png)
![bug2](https://user-images.githubusercontent.com/2393097/31650836-7bb27a6a-b319-11e7-83d8-77fb85fa33f2.png)
![bug3](https://user-images.githubusercontent.com/2393097/31650837-7bd00332-b319-11e7-94fb-d6e809b24182.png)

**Comment by axel-angel** [comment] 2017-10-17 07:32
I downgraded to 55 and it works again:
![before1](https://user-images.githubusercontent.com/2393097/31652036-0cacc864-b31e-11e7-896f-f7cf41d9efd9.png)

**Comment by grechaw** [comment] 2017-10-19 23:46
This bug is starting to make me go cross-eyed.  I wonder if there is some option that could remove the favicons from the completions...

**Comment by SammysHP** [comment] 2017-10-23 17:26
Duplicate of #796.

**Closed by SammysHP** 2017-10-23 17:26 UTC
