### ISSUE TITLE
`<C-i>` may get intercepted by website (editor cannot be opened from textarea)

### ISSUE THREAD

**Issue by blueyed** [vimperator/vimperator-labs#119] opened 2014-12-11 22:29 UTC
With Reddit comments, <c-i> toggles *italic* (see e.g. http://www.reddit.com/r/linux/comments/2p06nm/moreutils_a_growing_collection_of_the_unix_tools/) instead of opening the editor.

I am using a custom mapping, but removing it still makes it fail:

    :js mappings.addUserMap([modes.INSERT], ["<c-i>"], "Launch the external editor.", editExternallyWithOptions);

Remapping it to another key works:

`:js mappings.addUserMap([modes.INSERT], ["<c-x><c-i>"], "Launch the external editor.", editExternallyWithOptions);`

This is now my additional backup shortcut.

**Comment by sukima** [comment] 2015-01-22 02:22
I add `imap <C-S-I> <C-i>` to my [`~/.vimperatorrc`](https://github.com/sukima/dotfiles/blob/master/home/.vimperatorrc#L6) and it works as expected only I have to add the Shift key in those cases when `<C-i>` is intercepted.

**Comment by timss** [comment] 2016-03-01 22:35
Seems to be a duplicate of #34 (and possibly others?). Closing.

**Closed by timss** 2016-03-01 22:35 UTC
