### ISSUE TITLE
`i_<C-I>` won’t open Vim on GitHub

### ISSUE THREAD

**Issue by mcarton** [vimperator/vimperator-labs#469] opened 2016-03-24 19:13 UTC
##### Issue type:
Feature request (?)

##### Version:

```
Vimperator:	3.12.0 (created: 2016/02/28 22:07:56)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

GitHub has recently added `^I` as a shortcut to insert `_|_` (with `|` is the cursor position). This is excessively annoying as I frequently used `^I` to edit my issue/PR in Vim.

Is there a way to remove that behavior or open Vim in some other way?

##### Expected behavior:

It used to open Vim.

##### Steps to reproduce:

Open a PR/Issue on GitHub, hit `^I` in the big box. Vim won’t open, GitHub inserts `_|_`.

**Comment by timss** [comment] 2016-03-24 20:32
Thanks for reporting, however this is a duplicate of #384 so I'm closing this one.

For non-ignore `C-i`, there's also the relevant issue #34. The workaround suggested might be of interest, if just opening the editor is all you want:

    inoremap <C-S-i> <C-i>

**Closed by timss** 2016-03-24 20:32 UTC

**Comment by mcarton** [comment] 2016-03-24 21:02
This is a different problem from #384 really, but the workaround works. Thanks.

**Comment by benoit-pierre** [comment] 2016-03-24 21:09
The problem with this "workaround" is that when using the remapped shortcut, other shortcuts stop working while the editor is active.

**Comment by timss** [comment] 2016-03-24 22:01
@mcarton Oh right sorry, I was picturing ignore mode being relevant but of course you're right. Only #34 it is then. 

@benoit-pierre Other shortcuts? Please discuss them in #34, so we can keep it in one issue. Thanks :+1:
