### ISSUE TITLE
hlsearch only highlighting single match

### ISSUE THREAD

**Issue by willjp** [vimperator/vimperator-labs#734] opened 2017-03-05 16:40 UTC
##### Issue type:
- Bug report

##### Version:
Vimperator: 3.16.0 (created: 2017/02/01 00:55:15)
Firefox:       Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

##### Description:
When searching with ``set hlsearch`` on, only the current match is highlighted
(previously the current match was highlighted, and every other match was also highlighted)

##### Steps to reproduce:

```
:set hlsearch
/word-with-multiple-matches
# only one match is highligted at a time
```

**Comment by SammysHP** [comment] 2017-03-06 21:10
Duplicate of #676.

**Closed by SammysHP** 2017-03-06 21:10 UTC
