### ISSUE TITLE
[feature request] ignorekeys -only (blacklist)

### ISSUE THREAD

**Issue by losingkeys** [vimperator/vimperator-labs#645] opened 2016-11-23 00:41 UTC
##### Issue type:

- Feature request

##### Description:

`:ignorekeys` supports `-except`, allowing you to pass keys that should be whitelisted, so vimperator won't ignore those keys. I'd like the opposite to be available. For example if you wrote `:ignorekeys -only=j,k,<cr> duckduckgo.com`, vimperator would mostly be enabled on duckduckgo.com, but <kbd>j</kbd>, <kbd>k</kbd>, and <kbd>Enter</kbd> keys would be passed through to the website. Thanks for your consideration and the great plugin!

**Comment by drselump14** [comment] 2016-12-02 00:44
The feedsomekeys plugin can do that job 
( https://github.com/vimpr/vimperator-plugins/blob/master/feedSomeKeys_3.js)

However, I hope vimperator implement this feature without plugin

**Comment by timss** [comment] 2017-01-24 09:48
Closing as duplicate of #70. 

Thanks for submitting this issue, it should get the focus it deserves. PRs welcome!

**Closed by timss** 2017-01-24 09:48 UTC
