### ISSUE TITLE
:tabopen command no longer working as expected

### ISSUE THREAD

**Issue by jcshelby** [vimperator/vimperator-labs#699] opened 2017-02-06 14:35 UTC
##### Issue type:
- Bug report

##### Version:
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

##### Description:
The :tabopen command is no longer recognized after updating FF to its latest version. When attempting to use the command a message stating "Not a vimperator command: tabopen" is displayed. The workaround is to use ctrl-t to open a new tab and use the :open command to navigate to a new page

##### Expected behavior:
The tabopen command worked until the most recent version of FF was deployed and continues to work on older versions of FF. I would expect this command to be available and usable assuming it hasn't been deprecated (which seems unlikely since to the best of my knowledge vimperator hasn't updated since the last release in October)

##### Steps to reproduce:
Type :tabopen into the vimperator CLI with the same versions of FF and vimperator

**Comment by timss** [comment] 2017-02-06 15:21
Thanks for reporting this issue, but this seems to be a duplicate of #568 and was fixed in #675, ultimately released as [Vimperator 3.16](https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.16.0). New version coming on [AMO](https://addons.mozilla.org/en-US/firefox/addon/vimperator/) soon™.

**Closed by timss** 2017-02-06 15:21 UTC
