### ISSUE TITLE
Google search for images is buggy

### ISSUE THREAD

**Issue by ghost** [vimperator/vimperator-labs#57] opened 2014-10-14 16:11 UTC
1. go to google , select search for images and type out some search
2. select a particular image through hint mode
3. scrolling down using j and k keys is now becomes disabled

**Comment by timss** [comment] 2016-02-26 23:57
Can't reproduce. May be invalid as of #397.

Closing. Please notify if this is wrong.

**Closed by timss** 2016-02-26 23:57 UTC
