### ISSUE TITLE
Unable to use Vimperator in Firefox Developer Edition 47.0a2

### ISSUE THREAD

**Issue by billsykes** [vimperator/vimperator-labs#480] opened 2016-04-14 14:37 UTC
##### Issue type:

- Bug report

##### Version:

Unable to post :version output as vimperator does not seem to load. According to the addons page this is version 3.12.0.

Running on OSX Yosemite (10.10.5).

##### Description:

After installing vimperator and restarting Firefox Developer edition v47.0a2 vimperator fails to open when pressing any key that should open it ('o' for example). Attempting to open the vimperator preferences results in a blank window appearing:

![screen shot 2016-04-14 at 10 32 10 am](https://cloud.githubusercontent.com/assets/1043337/14531656/34829e76-022c-11e6-8554-8e1ec85d5846.png)

It should also be noted that I created a new Firefox profile in order to ensure this is the only addon installed. In the non-developer version of FireFox (v45.0.2) Vimperator is working just fine for me.

##### Expected behavior:

That the vimperator console should open, and that navigating to preferences should not produce a blank window.

##### Steps to reproduce:

Open a tab and attempt to press 'o', nothing happens.  Go to the addons page and click preferences for Vimperator and only a blank window appears.

**Comment by gkatsev** [comment] 2016-04-14 15:30
Yeah, unfortunately, it's broken. Closing as a duplicate of #441.

**Closed by gkatsev** 2016-04-14 15:30 UTC
