### ISSUE TITLE
unable to go back to normal mode from <select> form

### ISSUE THREAD

**Issue by sohorx** [vimperator/vimperator-labs#204] opened 2015-03-13 14:57 UTC
hi, first thanks for vimperator.

I'm on archlinux,
Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
Vimperator:	3.9 (created: 2015/02/15 15:49:05)

as the title say, i'm unable to go back to normal mode by pressing escape (or shift escape) a multiple time when going into a select form, that's only close it.
the only way i found is to click with the mouse somewhere else.

**Comment by gkatsev** [comment] 2015-03-13 15:21
This is a dupe of #28

**Closed by gkatsev** 2015-03-13 15:21 UTC

**Comment by gkatsev** [comment] 2015-03-13 15:23
Or rather, #46
