### ISSUE TITLE
:jumps does not work any more

### ISSUE THREAD

**Issue by xuhdev** [vimperator/vimperator-labs#545] opened 2016-06-20 21:14 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
```

Calling `:jumps` gives an error message `TypeError:  is not iterable`.

**Comment by timss** [comment] 2016-06-20 21:42
Thanks for reporting. 
Closing as duplicate of #508

**Closed by timss** 2016-06-20 21:42 UTC
