### ISSUE TITLE
Incompatible with Firefox Developer Edition 40.0a2

### ISSUE THREAD

**Issue by diefans** [vimperator/vimperator-labs#229] opened 2015-05-19 11:49 UTC
The new release of Firefox developer edition with enabled multiprocess feature breaks some vimperator features:

- form input is not possible: all vimperator bound keys get triggered
- find is not working: TypeError: window.gFindBar.browser.finder._highlight is not a function

**Comment by dkns** [comment] 2015-05-19 21:36
I just upgraded (literally 5 minutes ago) to 40.0a2 and find (/) is working fine for me. Not sure what you mean by 'form input is not possible.'

**Comment by gkatsev** [comment] 2015-05-19 21:37
Make sure you have `e10s` disabled. is it enabled by default yet?
Also, the `_highlight` `TypeError` seems like an issue we've fixed previously. What version of vimperator are your unning?

**Comment by dkns** [comment] 2015-05-19 21:42
To add to my previous comment: just checked and electrolysis is disabled for me.

**Comment by diefans** [comment] 2015-05-20 06:18
I had e10s enabled. with e10s disabled all is fine. thanks!

**Comment by gkatsev** [comment] 2015-05-20 15:59
Cool. In that case, I'll close it as a duplicate of #211.

**Closed by gkatsev** 2015-05-20 15:59 UTC
