### ISSUE TITLE
:

### ISSUE THREAD

**Issue by AlekseyBuzmakov** [vimperator/vimperator-labs#804] opened 2017-10-16 05:57 UTC
##### Issue type:y:
- Bug report

##### Version:
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:56.0) Gecko/20100101 Firefox/56.0

##### Description:
After apt-get upgrade vimperator stopped working. Follow hint does not show anything: no hints. When typing column ':' the completion showing just on the page with no background (before it was on a white background and thus it was not mixed with the content of the page). See "open tab" example in the figure ![screenshot - 16 10 2017 - 10 55 06](https://user-images.githubusercontent.com/11535618/31597214-b2f857ec-b260-11e7-919e-3ed94ce3b161.png)

##### Expected behavior:

Hints are expected to be visible, Completion page is expected to be well visible (not mixed with the content of the page).

##### Steps to reproduce:

On my computer it is reproducible on any web page, e.g., google.com

**Comment by zunsthy** [comment] 2017-10-18 05:43
Duplicate of #777 .

**Comment by SammysHP** [comment] 2017-10-23 17:26
Duplicate of #796.

**Closed by SammysHP** 2017-10-23 17:26 UTC
