### ISSUE TITLE
Dont list historys when I use `:open` in firefoxDeveloperEdition 49.0a2 

### ISSUE THREAD

**Issue by Geng-G-Razor** [vimperator/vimperator-labs#539] opened 2016-06-17 03:10 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0
```

##### Description:

When I press `o` and type some strings, it should list matching historys in old version firefox, and so i can reach my wanting website quick.
But now it can't work, I feel very frustrated and upset for this, I dont know how to visit the internet without this feature. Please help.

##### Expected behavior:

Please put this feature back in the latest version of firefox

##### Steps to reproduce:

press `o`, or command line `:open`, `t` for the same

**Comment by gkatsev** [comment] 2016-06-17 03:15
Closing as a duplicate of #538. I've renamed that one to be more general.

**Closed** 2016-06-17 03:16 UTC
