### ISSUE TITLE
Alert bell when opening link

### ISSUE THREAD

**Issue by rdgoite** [vimperator/vimperator-labs#727] opened 2017-02-26 13:39 UTC
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Every time I following a link using Vimperator's follow link feature (<kbd>F</kbd> or <kbd>Shift + F</kbd>), I hear the alert bell for my system as if something unexpected happened. I'm not really sure how to debug if there are actual errors so I can't provide any further details.

Aside from the alert bell, every thing seems to work as expected.

##### Expected behavior:

Link opens with no alert bell (that may indicate some unexpected errors).

##### Steps to reproduce:

Follow link using either <kbd>F</kbd> or <kbd>Shift + F</kbd> (or whatever is set in the system).

**Comment by rndusr** [comment] 2017-02-26 21:56
duplicate of #718

**Comment by timss** [comment] 2017-04-09 12:32
Thanks @rndusr, closing as of #720.

**Closed by timss** 2017-04-09 12:32 UTC
