### ISSUE TITLE
Command bar style broken in Firefox 56

### ISSUE THREAD

**Issue by dapicester** [vimperator/vimperator-labs#793] opened 2017-09-30 03:16 UTC
##### Issue type:

- Bug report

##### Version:
``` 
Vimperator: 3.16.0 (created: 2017/02/01 00:55:15)
Firefox: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:56.0) Gecko/20100101 Firefox/56.0
```

##### Description:

The command bar is not styled as usual, see the following screenshot:
<img width="764" alt="vimperator" src="https://user-images.githubusercontent.com/3007132/31041820-128c6c74-a5ce-11e7-8016-c127173b5a01.png">

##### Expected behavior:

The bar should be styled normally, as shown in the [vimperator home page](http://vimperator.org/).

##### Steps to reproduce:

1. Install or Update Firefox 56
2. Install or Update Vimperator (latest is 3.16.0)

**Comment by SammysHP** [comment] 2017-09-30 18:09
Duplicate of #777.

**Closed by SammysHP** 2017-09-30 18:09 UTC
