### ISSUE TITLE
Vimperator can't gain focus against Google

### ISSUE THREAD

**Issue by MPW1412** [vimperator/vimperator-labs#14] opened 2014-07-22 08:49 UTC
Hello,

I love the vimperator plugin. But I can't use it on any google page. Google grabs the focus to its search field.

After pressing ESC and then pressing any key, the focus returns to the google text field and the char is inserted there.

Firefox 30.0, Ubuntu 12.04 64bit.

Thanks for reading
MPW

**Comment by Koward** [comment] 2015-05-23 13:43
I confirm this is still not solved as today 23 may 2015 on Ubuntu. You have to use the mouse as soon as you open your browser if your front page is Google. You can still reproduce it the same way MPW1412 did.

**Comment by MPW1412** [comment] 2015-05-23 13:47
The curious thing is, on two pcs with Ubuntu it works perfectly. I can't find any difference in the configuration.

Is there a way to dump the configuration and compare it?

**Comment by Koward** [comment] 2015-05-23 14:16
For the whole configuration of Ubuntu, I don't think so, but parts of it probably.
Concerning Vimperator itself, I was able to fix this by adding an autocmd and setting focuscontent in my .vimperatorrc, but it's not working using the stock settings.
Maybe could you try without any personal change ?

**Comment by maxauthority** [comment] 2015-05-25 15:54
I recently noticed that pressing Esc and : also does not open the command
line when google.com is open. This will be quite serious, but probably has
something to do which keys (keydown/keypress/etc.) we handle. By fixing one
site we seem to "unfix" another :(

**Comment by MPW1412** [comment] 2015-06-09 07:14
I recently noticed, that it occurs much less often, if you activate the vi status bar. Which is unfortunatly not hidden, if you watch html5 videos on fullscreen. But for standard mode, this is a nice workaround.

And Ctrl + Alt Gr + 8 (german Keyboard for [) works much better to escape, than button escape.

**Comment by pelegm** [comment] 2015-07-29 07:17
I confirm the bug on Ubuntu 14.04.2 with Vimperator 3.9. I also confirm that <kbd>Ctrl</kbd>-<kbd>[</kbd> works perfectly.

This bug kills many of my mappings. For example, this one:
```vim
map sgo Y:tabopen<Space>google<Space><S-Insert><Return>
```

I know this one can be achieved by <kbd>P</kbd>, but not if `google` is not my `defsearch`.

**Comment by anjiannian** [comment] 2015-09-16 16:01
hello guys, 
I get worse. I cant get the focus out the google search bar with <Esc>, mouse clicking or set focus content. I have to click the tabs to go forward.

vimperator : 3.10.1
firefox 40.0.3
mac osx 10.10.5

thanks,

**Comment by Enzime** [comment] 2015-09-17 01:58
Have you tried building vimperator from GitHub master? There's a fix for this in one of the commits that aren't in a release yet, although the mouse clicking not allowing you to lose focus may mean it's something else.

**Comment by xerebz** [comment] 2015-11-05 01:10
I'm pretty sure this is because some sites remap the escape key. Ctrl+[ works but keycode 27 (esc) is hijacked by some javascript.

**Comment by maxauthority** [comment] 2015-11-22 19:43
Yeah, git master should work. I guess I'll release a new vimperator version
soon!

**Comment by pjvds** [comment] 2015-11-24 08:34
Great news! Looking forward to the new version :+1:

**Comment by MPW1412** [comment] 2015-11-24 09:12
Thanks for your work! I still love the vimperator and use it on all my pcs. I'm looking forward to the new version!

**Comment by timss** [comment] 2016-05-06 09:12
A lot has changed since this was reported, and behavior can be a bit different on different platforms, desktops etc. Not able to reproduce with FF 45, Vimperator 3.13.0 without config and KWin (Linux), so closing for now. 

Please shout out of you're still able to reproduce in latest release, and it'll be reopened or redirected to another/new issue. Thanks.

**Closed by timss** 2016-05-06 09:12 UTC
Labels: medium

**Comment by oysteinkrog** [comment] 2016-05-06 16:10
I can also no longer repro :)
FF 46, Win64, Vimperator 3.13.0.

**Comment by MPW1412** [comment] 2016-05-06 18:01
Seems to be fixed in 3.13.0.

**Comment by timss** [comment] 2016-05-06 18:47
Great, thanks for confirming.
