### ISSUE TITLE
colorscheme causes significant slowdown

### ISSUE THREAD

**Issue by edio** [vimperator/vimperator-labs#45] opened 2014-09-29 15:40 UTC
Firefox freezes for several (up to 10) seconds when opening new window (either private or normal) if colorscheme directive is present in .vimperatorrc. During the freeze firefox consumes vast amount of CPU time.

firefox version: 32.0.3
os: archlinux x86_64
vimperator version: 3.8.2

**Comment by blueyed** [comment] 2015-03-19 15:34
Is this fixed now with #52 being merged?

**Comment by blueyed** [comment] 2015-03-19 15:42
Was this caused by `hi clear`?
Or would `hi clear` mean that the optimization gets skipped?

There is a similar issue for Pentadactyl at https://code.google.com/p/dactyl/issues/detail?id=1150 - and a fix to the pentadactyl-solarized theme at https://github.com/claytron/pentadactyl-solarized/commit/533ad4429c82395697ee9227541b3d1bce18582d (removing the `hi clear` as a workaround).

**Comment by gkatsev** [comment] 2016-01-27 05:01
@caisui did you ever make a PR for this? Would be great to get it in.

**Comment by timss** [comment] 2016-05-06 09:28
I believe this was resolved in #52 (thanks again). 

Closing, unless anyone is still having this issue.

**Closed by timss** 2016-05-06 09:28 UTC
