### ISSUE TITLE
gi did not work

### ISSUE THREAD

**Issue by jwvim** [vimperator/vimperator-labs#146] opened 2015-01-18 08:28 UTC
When I type gi in google or other search engines, it said:

TypeError: 'snapshotLength' getter called on an object tha does not implement interface XPathResult

Vimperator 3.8.3
Firefox 35

**Comment by gkatsev** [comment] 2015-01-18 18:34
Dupe of #33. If you try the latest alpha in github releases, it should have this fixed. Please comment in #33 if you find that is not the case. Thanks!

**Closed by gkatsev** 2015-01-18 18:34 UTC
