### ISSUE TITLE
Vimperator doesn't autocomplete with bookmarks

### ISSUE THREAD

**Issue by artemisclyde** [vimperator/vimperator-labs#603] opened 2016-10-02 18:23 UTC
##### Issue type:
- Bug report

##### Version:
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0

##### Description:
Usually when you open a new tab or window via Vimperator, the tabopen command will have autocompletion for bookmarks saved in ffx. This used to happen, but now it doesn't anymore.

##### Expected behavior:
As was state before, it would be lovely if Vimperator autocompleted the tabopen, open etc. commands with the saved bookmarks.

##### Steps to reproduce:
Use tabopen or open and you'll see that bookmarks are not shown.

**Comment by zoni** [comment] 2016-10-03 08:26
I've run into this recently as well. I'm 90% sure an upgrade of FireFox itself triggered this.

The default complete option of `complete=sl` only shows search suggestions. I think it's the `l` option (FF location bar entries) specifically that's broken.

Using `:set complete=sbh` for example works fine (and can be used as a workaround in the mean time, it yields somewhat comparable results).

**Comment by timss** [comment] 2016-10-03 08:50
Thanks for the report.

Sounds like a duplicate of #590. Intended fix merged in #591. Temporary workaround [here](https://github.com/vimperator/vimperator-labs/issues/590#issuecomment-248833125).

**Closed by timss** 2016-10-03 08:50 UTC
Labels: compatibility, duplicate

**Comment by artemisclyde** [comment] 2016-10-06 09:44
@zoni That's so far the best workaround for me, thanks!
