### ISSUE TITLE
tabopen broken in firefox 51

### ISSUE THREAD

**Issue by mpnordland** [vimperator/vimperator-labs#607] opened 2016-10-05 13:24 UTC
##### Issue type:

- Version compatibility

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### 
tabopen does not function, instead the error "Not a vimperator command: tabopen google.com"
is shown

##### Expected behavior:

Pressing t or typing tabopen should autocomplete and open in a new tab

##### Steps to reproduce:
type :tabopen <site/autocomplete>

**Comment by stepshal** [comment] 2016-10-05 14:33
Same issue: https://github.com/vimperator/vimperator-labs/issues/568

**Comment by gkatsev** [comment] 2016-10-06 06:26
Yup, closing as duplicate of #568.

**Closed by gkatsev** 2016-10-06 06:26 UTC
Labels: compatibility
